"use strict";

const fs = require("fs");
const vm = require("vm");
const assert = require("assert");

const sandbox = { console, Math };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync("src/config.js", "utf8") + "\nglobalThis.CONFIG = CONFIG;", sandbox);
vm.runInContext(fs.readFileSync("src/core.js", "utf8"), sandbox);
vm.runInContext(fs.readFileSync("src/game.js", "utf8") + "\nglobalThis.game = game;", sandbox);
const { CONFIG } = sandbox;
const { game } = sandbox;
sandbox.FloatText = class FloatText { constructor(x, y, text, color) { this.x = x; this.y = y; this.text = text; this.color = color; } };
sandbox.Shockwave = class Shockwave { constructor(x, y, maxR, color) { this.x = x; this.y = y; this.maxR = maxR; this.color = color; } };
sandbox.pools = {
  enemy: { get(type, x, y, move, elite) { return { type, x, y, move, elite, dead: false, isBoss: false, radius: CONFIG.enemy[type].radius }; } },
  enemyBullet: { get(x, y, vx, vy, damage) { return { x, y, vx, vy, damage, dead: false }; } },
  homingShot: { get(x, y, overcharge) { return { x, y, overcharge }; } },
};
sandbox.Sound = { powerup() {}, tone() {} };
vm.runInContext(fs.readFileSync("src/entities.js", "utf8") + "\nglobalThis.Enemy = Enemy; globalThis.Missile = Missile; globalThis.PlayerLaser = PlayerLaser;", sandbox);
const { Enemy, Missile, PlayerLaser } = sandbox;

const between = (value, min, max, label) => assert(value >= min && value <= max, `${label} ${value} outside ${min}-${max}`);
const unique = (items, label) => assert.strictEqual(new Set(items).size, items.length, `${label} has duplicate keys`);

assert(CONFIG && CONFIG.player && CONFIG.endless, "CONFIG did not load");

between(CONFIG.powerup.chipMinEndlessTime, 15, 30, "first endless draft delay");
between(CONFIG.powerup.chipDraftInterval, 15, 30, "endless draft interval");
between(CONFIG.powerup.chipBossDraftDelay, 15, 30, "boss draft delay");
between(CONFIG.powerup.chipMinDraftGap, 15, 30, "minimum endless draft gap");
between(CONFIG.endless.maxEnemies, 8, 20, "endless max enemies");
between(CONFIG.endless.enemyHpRampMult, 1.5, 3.2, "endless enemy HP ramp");
between(CONFIG.endless.dmgRampMult, 1.5, 3.5, "endless damage ramp");
between(CONFIG.endless.boss.firstDelay, 20, 45, "first boss delay");
between(CONFIG.endless.boss.interval, 25, 55, "boss interval");
between(CONFIG.bossPhase.weakDuration, 1.5, 4, "boss phase weak duration");
between(CONFIG.bossPhase.weakDamageMult, 0.1, 0.45, "boss phase weak damage");
between(CONFIG.endless.eventClearScore, 300, 1800, "event clear score");
between(CONFIG.endless.eventCleanShield, 8, 50, "event clean shield");
between(CONFIG.endless.eventCleanShieldDur, 2, 10, "event clean shield duration");

const enemyKeys = new Set(Object.keys(CONFIG.enemy));
const shieldCarrier = CONFIG.enemy.shieldCarrier;
assert(shieldCarrier, "enemy variety should include shield carrier");
between(shieldCarrier.hp, 10, 30, "shieldCarrier hp");
between(shieldCarrier.shield, 8, 40, "shieldCarrier shield");
between(shieldCarrier.fireInterval, 1.2, 2.8, "shieldCarrier fireInterval");
const eliteTypes = CONFIG.elite.types || [];
unique(eliteTypes, "elite types");
assert(eliteTypes.length >= 5, "elite type variety should include at least 5 types");
assert(eliteTypes.includes("jammer"), "elite type variety should include jammer");
for (const key of eliteTypes) {
  const e = CONFIG.elite[key];
  assert(e && e.name && e.color, `elite ${key} needs readable text`);
  if (e.hpMult) between(e.hpMult, 0.75, 1.35, `elite ${key} hpMult`);
  if (e.speedMult) between(e.speedMult, 1, 1.45, `elite ${key} speedMult`);
  if (e.fireMult) between(e.fireMult, 0.6, 1, `elite ${key} fireMult`);
  if (e.regenEvery) between(e.regenEvery, 1.5, 4, `elite ${key} regenEvery`);
  if (e.regenPct) between(e.regenPct, 0.03, 0.12, `elite ${key} regenPct`);
  if (e.jamRadius) between(e.jamRadius, 140, 280, `elite ${key} jamRadius`);
  if (e.weaponSlow) between(e.weaponSlow, 1.05, 1.4, `elite ${key} weaponSlow`);
}
game.boss = null; game.enemies = [{ dead: false, x: 100, y: 100, radius: 20, type: "medium", eliteCfg: CONFIG.elite.jammer }];
assert(game.jamFactor(100, 100) > 1, "jammer elite should slow weapons in range");
assert.strictEqual(game.jamFactor(500, 100), 1, "jammer elite should not slow weapons out of range");
const jammedWithoutFilter = game.jamFactor(100, 100);
game.bonuses = { signalFilter: 1 };
assert(game.jamFactor(100, 100) < jammedWithoutFilter, "signalFilter should reduce jammer slow");
game.bonuses = {};
for (const [i, pool] of CONFIG.endless.pools.entries()) {
  assert(pool.enemies && pool.enemies.length, `endless pool ${i} is empty`);
  for (const type of pool.enemies) assert(enemyKeys.has(type), `pool ${i} references missing enemy ${type}`);
}

const eventKeys = CONFIG.endless.events.map(e => e.key);
unique(eventKeys, "endless events");
assert(eventKeys.includes("repairConvoy"), "endless events should include repair convoy pressure");
assert(eventKeys.includes("shieldWall"), "endless events should include shield carrier pressure");
assert(eventKeys.includes("phantomWing"), "endless events should include phantom pressure");
assert(eventKeys.includes("carrierRaid"), "endless events should include carrier split pressure");
assert(eventKeys.includes("annihilationOrder"), "endless events should include a kill-goal objective");
assert(eventKeys.includes("aceHunt"), "endless events should include an elite hunt objective");
assert(eventKeys.includes("noHitRun"), "endless events should include a no-hit objective");
assert(eventKeys.includes("crossfire"), "endless events should include a side bullet hazard");
const routeNames = new Set(["主炮", "激光", "追踪", "导弹", "生存", "风险"]);
const drops = new Set(["power", "heal", "bomb", "wing", "chip"]);
for (const e of CONFIG.endless.events) {
  assert(e.name && e.sub, `event ${e.key} needs readable text`);
  if (e.routeBias) assert(routeNames.has(e.routeBias), `event ${e.key} has invalid routeBias ${e.routeBias}`);
  if (e.minTime != null) between(e.minTime, 0, 300, `event ${e.key} minTime`);
  if (e.enemyType) assert(enemyKeys.has(e.enemyType), `event ${e.key} references missing enemy ${e.enemyType}`);
  if (e.enemyChance != null) between(e.enemyChance, 0, 0.75, `event ${e.key} enemyChance`);
  if (e.eliteChance != null) between(e.eliteChance, 0, 0.9, `event ${e.key} eliteChance`);
  if (e.spawnBonus != null) between(e.spawnBonus, 0, 3, `event ${e.key} spawnBonus`);
  if (e.killGoal != null) between(e.killGoal, 6, 30, `event ${e.key} killGoal`);
  if (e.eliteGoal != null) between(e.eliteGoal, 2, 10, `event ${e.key} eliteGoal`);
  if (e.noHitGoal != null) assert.strictEqual(e.noHitGoal, true, `event ${e.key} noHitGoal should be true when present`);
  if (e.scoreBonus != null) between(e.scoreBonus, 0, 0.35, `event ${e.key} scoreBonus`);
  if (e.threatGainMult != null) between(e.threatGainMult, 1, 1.5, `event ${e.key} threatGainMult`);
  if (e.forceDrop) assert(drops.has(e.forceDrop), `event ${e.key} has invalid forceDrop ${e.forceDrop}`);
  if (e.powerupChanceAdd != null) between(CONFIG.endless.powerupChance + e.powerupChanceAdd, 0, 0.4, `event ${e.key} total powerup chance`);
  if (e.enemyHpMult != null) between(e.enemyHpMult, 0, 0.6, `event ${e.key} enemyHpMult`);
  if (e.laserEvery) {
    between(e.laserEvery, 3, 7, `event ${e.key} laserEvery`);
    between(e.warn || 0, 0.4, 1.2, `event ${e.key} laser warn`);
    between(e.width || 0, 20, 70, `event ${e.key} laser width`);
  }
  if (e.bulletEvery) {
    between(e.bulletEvery, 2.5, 6, `event ${e.key} bulletEvery`);
    between(e.bulletRows || 0, 3, 8, `event ${e.key} bulletRows`);
    between(e.bulletSpeed || 0, 160, 360, `event ${e.key} bulletSpeed`);
    between(e.bulletDamage || 0, 3, 12, `event ${e.key} bulletDamage`);
  }
}
const repairConvoy = CONFIG.endless.events.find(e => e.key === "repairConvoy");
assert.strictEqual(repairConvoy.enemyType, "support", "repair convoy should force support enemies");
assert(repairConvoy.minTime >= 90, "repair convoy should be a mid/late endless event");
const phantomWing = CONFIG.endless.events.find(e => e.key === "phantomWing");
assert.strictEqual(phantomWing.enemyType, "phantom", "phantom wing should force phantom enemies");
assert(phantomWing.minTime >= 120, "phantom wing should be a late endless event");
assert(phantomWing.routeBias, "phantom wing should bias draft choices");
const carrierRaid = CONFIG.endless.events.find(e => e.key === "carrierRaid");
assert.strictEqual(carrierRaid.enemyType, "carrier", "carrier raid should force carrier enemies");
assert(carrierRaid.minTime >= 150, "carrier raid should be a late endless event");
assert(CONFIG.enemy.carrier.spawns, "carrier raid should rely on carrier split adds");
const shieldWall = CONFIG.endless.events.find(e => e.key === "shieldWall");
assert.strictEqual(shieldWall.enemyType, "shieldCarrier", "shield wall should force shield carriers");
assert(shieldWall.minTime >= 120, "shield wall should be a mid/late endless event");
assert(CONFIG.endless.pools.slice(3).some(pool => pool.enemies.includes("shieldCarrier")), "late endless pools should include shield carriers");
const aceHunt = CONFIG.endless.events.find(e => e.key === "aceHunt");
assert.strictEqual(aceHunt.enemyType, "gunner", "ace hunt should force durable gunner elites");
assert(aceHunt.minTime >= 90, "ace hunt should be a mid endless event");
assert(aceHunt.eliteChance >= 0.6, "ace hunt should reliably spawn elites");
assert(aceHunt.eliteGoal >= 3, "ace hunt should require multiple elite kills");
const noHitRun = CONFIG.endless.events.find(e => e.key === "noHitRun");
assert(noHitRun.minTime >= 60, "no-hit run should not appear immediately");
assert.strictEqual(noHitRun.routeBias, "生存", "no-hit run should bias survival drafts");
assert.strictEqual(noHitRun.noHitGoal, true, "no-hit run should require no hits");
const crossfire = CONFIG.endless.events.find(e => e.key === "crossfire");
assert(crossfire.minTime >= 90, "crossfire should be a mid endless hazard");
assert.strictEqual(crossfire.routeBias, "生存", "crossfire should bias survival drafts");
game.enemyBullets = []; game.floats = []; game.endless = true; game._endlessT = crossfire.minTime; game.threat = 0; game._endlessHazardT = 0; game._rng = () => 0.25;
assert.strictEqual(game.updateEndlessBulletEvent(0, crossfire), crossfire.bulletRows, "crossfire should spawn one side bullet row set");
assert.strictEqual(game.enemyBullets.length, crossfire.bulletRows, "crossfire should create enemy bullets");
assert(game.enemyBullets.every(b => b.vx > 0), "crossfire side bullets should move horizontally from the side");
assert(game.endlessEventHUDDetail(crossfire).includes("侧弹"), "crossfire HUD should show bullet cadence");
const recentEventKeys = CONFIG.endless.events.slice(0, 2).map(e => e.key);
game.endless = true; game._endlessT = 999; game._endlessEvent = null; game._endlessRecentEvents = recentEventKeys.slice(); game._endlessEventsSeen = []; game._endlessStats = { events: 0, hits: 0 }; game._rng = () => 0;
game.triggerEndlessEvent();
assert(!recentEventKeys.includes(game._endlessEvent.key), "endless event picker should avoid recent repeats when possible");
assert.strictEqual(game._endlessRecentEvents[0], game._endlessEvent.key, "endless event picker should remember the newest event");
assert(game._endlessRecentEvents.length <= 2, "endless event memory should stay short");
game.score = 0; game.threat = 0; game.bonuses = {}; game.chips = {}; game.floats = []; game._bonusRerolls = 0; game._endlessEventTimer = 0; game._endlessStats = { hits: 2 }; game._endlessEventStartHits = 1;
game.player = { x: 100, y: 100, shieldHp: 0, grantShield(n, dur) { this.shieldHp = n; this.shieldTimer = dur; } };
const eventHitGain = game.finishEndlessEvent(CONFIG.endless.events[0]);
assert.strictEqual(eventHitGain, CONFIG.endless.eventClearScore, "event clear should grant base score after hits");
assert.strictEqual(game.player.shieldHp, 0, "event clear should not grant clean shield after hits");
assert.strictEqual(game._bonusRerolls, 0, "hit event clear should not grant bonus rerolls");
assert.strictEqual(game._endlessStats.eventClears, 1, "event clear should be tracked");
assert.strictEqual(game._endlessStats.cleanEvents || 0, 0, "hit event clear should not count as clean");
assert.strictEqual(game._endlessStats.eventScore, eventHitGain, "event score should be tracked");
const killGoalEvent = CONFIG.endless.events.find(e => e.key === "annihilationOrder");
game.score = 0; game.floats = []; game._endlessStats = { hits: 0, kills: 3, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 0; game._endlessEventStartKills = 0;
assert.strictEqual(game.finishEndlessEvent(killGoalEvent), 0, "kill-goal event should fail without enough kills");
assert.strictEqual(game._endlessStats.eventClears, 0, "failed kill-goal event should not count as cleared");
assert.strictEqual(game._endlessStats.eventFails, 1, "failed kill-goal event should be tracked");
assert(game.floats.some(f => f.text.includes("目标未达成")), "failed kill-goal event should show feedback");
game._endlessStats.kills = 7; game._endlessEventStartKills = 3;
assert(game.endlessEventHUDDetail(killGoalEvent).includes("4/" + killGoalEvent.killGoal), "kill-goal event HUD should show live progress");
assert(game.endlessReviewTags({ telemetry: game._endlessStats, time: 60, bonuses: {} }).some(t => t.includes("目标失败")), "failed kill-goal events should appear in review tags");
game.score = 0; game.floats = []; game._endlessStats = { hits: 0, kills: killGoalEvent.killGoal, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 0; game._endlessEventStartKills = 0;
assert(game.finishEndlessEvent(killGoalEvent) > 0, "kill-goal event should clear after enough kills");
assert.strictEqual(game._endlessStats.eventClears, 1, "cleared kill-goal event should count as cleared");
assert(game.endlessEventHUDDetail(killGoalEvent).includes(killGoalEvent.killGoal + "/" + killGoalEvent.killGoal), "kill-goal event HUD should show objective");
game.score = 0; game.floats = []; game._endlessStats = { hits: 0, eliteKills: 1, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 0; game._endlessEventStartEliteKills = 0;
assert.strictEqual(game.finishEndlessEvent(aceHunt), 0, "elite-goal event should fail without enough elite kills");
assert.strictEqual(game._endlessStats.eventClears, 0, "failed elite-goal event should not count as cleared");
assert.strictEqual(game._endlessStats.eventFails, 1, "failed elite-goal event should be tracked");
assert(game.floats.some(f => f.text.includes("王牌未击破")), "failed elite-goal event should show feedback");
game._endlessStats.eliteKills = 3; game._endlessEventStartEliteKills = 1;
assert(game.endlessEventHUDDetail(aceHunt).includes("2/" + aceHunt.eliteGoal), "elite-goal event HUD should show live progress");
game.score = 0; game.floats = []; game._endlessStats = { hits: 0, eliteKills: aceHunt.eliteGoal, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 0; game._endlessEventStartEliteKills = 0;
assert(game.finishEndlessEvent(aceHunt) > 0, "elite-goal event should clear after enough elite kills");
assert.strictEqual(game._endlessStats.eventClears, 1, "cleared elite-goal event should count as cleared");
assert(game.endlessReviewTags({ telemetry: { eliteKills: 8 }, time: 90, bonuses: {} }).some(t => t.includes("精英猎手")), "elite kill review should tag elite hunters");
game.score = 0; game.floats = []; game._endlessStats = { hits: 2, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 1;
assert.strictEqual(game.finishEndlessEvent(noHitRun), 0, "no-hit event should fail after taking a hit");
assert.strictEqual(game._endlessStats.eventClears, 0, "failed no-hit event should not count as cleared");
assert.strictEqual(game._endlessStats.eventFails, 1, "failed no-hit event should be tracked");
assert(game.floats.some(f => f.text.includes("无伤失败")), "failed no-hit event should show feedback");
assert(game.endlessEventHUDDetail(noHitRun).includes("受击1/1"), "no-hit event HUD should show failed hit progress");
game.score = 0; game.floats = []; game._endlessStats = { hits: 1, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 1;
assert(game.endlessEventHUDDetail(noHitRun).includes("受击0/1"), "no-hit event HUD should show clean progress");
assert(game.finishEndlessEvent(noHitRun) > 0, "no-hit event should clear without hits");
assert.strictEqual(game._endlessStats.eventClears, 1, "cleared no-hit event should count as cleared");
game.score = 0; game.floats = []; game._bonusRerolls = 0; game._endlessStats = { hits: 1 }; game._endlessEventStartHits = 1;
const eventCleanGain = game.finishEndlessEvent(CONFIG.endless.events[0]);
assert(eventCleanGain > eventHitGain, "clean event clear should grant bonus score");
assert(game.player.shieldHp >= CONFIG.endless.eventCleanShield, "clean event clear should grant shield");
assert.strictEqual(game._bonusRerolls, 1, "clean event clear should bank one bonus reroll");
assert.strictEqual(game._endlessStats.cleanEvents, 1, "clean event clear should be tracked");
game._endlessT = 60; game.beginChipDraft();
assert.strictEqual(game._chipRerolls, 2, "clean event reroll should apply to the next draft");
assert.strictEqual(game._bonusRerolls, 0, "bonus reroll bank should be consumed by the next draft");
assert(game.endlessReviewTags({ telemetry: game._endlessStats, time: 60, bonuses: {} }).some(t => t.includes("完美空域")), "clean event clears should appear in review tags");
assert(game.endlessReviewTags({ telemetry: { hits: 6, damageTaken: 120 }, time: 60, bonuses: {} }).some(t => t.includes("建议补生存")), "high damage review should suggest survival");
assert(game.endlessReviewTags({ telemetry: { bossKills: 0 }, time: 60, bonuses: {}, bossAffixes: ["蜂群·近卫舰"] }).some(t => t.includes("Boss输出")), "boss pressure review should suggest boss damage");
assert(game.endlessReviewTags({ telemetry: {}, time: 60, bonuses: { missileRack: 2 } }).some(t => t.includes("建议续构")), "near-ready route review should suggest route continuation");

const draftIds = CONFIG.chipOrder.map(k => "chip:" + k).concat(CONFIG.bonusOrder.map(k => "bonus:" + k));
const hasSurvivalDraft = () => game._chipChoices.some(id => id.startsWith("bonus:") && game.draftCardRoute(game.cardInfo(id)) === "生存");
const hasHpDraft = () => game._chipChoices.some(id => game.isHpDraftCard(id));
const hasMaxHpDraft = () => game._chipChoices.some(id => game.isMaxHpDraftCard(id));
const hasDraftRoute = route => game._chipChoices.some(id => game.draftCardRoute(game.cardInfo(id)) === route);
game.endless = true; game.player = { power: CONFIG.powerup.chipMinPower }; game._endlessEvent = null; game._endlessEventTimer = 0; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
assert.strictEqual(game.canDrop("chip"), false, "endless should use timed drafts instead of chip drops");
game.drawChipChoices();
assert(game._chipChoices.some(id => id.startsWith("bonus:")), "endless draft should include one permanent bonus option");
assert(hasSurvivalDraft(), "endless draft should include one survival/HP option");
assert(hasHpDraft(), "endless draft should include one HP/sustain option");
assert(hasMaxHpDraft(), "endless draft should include one max HP growth option");
assert(game.draftHpText(game.cardInfo("bonus:maxHp")).includes("血量"), "HP draft cards should show readable HP tag");
game.player = { power: CONFIG.powerup.chipMinPower, hp: 100, maxHp: 100 }; game._endlessT = 60; game._endlessStats = { hits: 0, damageTaken: 0 }; game.bonuses = {}; game.chips = {}; game._endlessEvent = null; game._endlessEventTimer = 0;
const armorPlatingBaseWeight = game.draftCardWeight("bonus:armorPlating");
game.player.hp = 35;
assert(game.hasSurvivalPressure(), "low HP should count as survival pressure");
assert(game.draftCardWeight("bonus:armorPlating") > armorPlatingBaseWeight, "survival pressure should weight survival cards higher");
assert(game.draftSurvivalText(game.cardInfo("bonus:armorPlating")).includes("生存"), "survival pressure cards should show reason text");
game.player.hp = 100; game._endlessStats = { hits: 5, damageTaken: 120 }; game._chipChoices = []; game._rng = () => 0.999;
assert(game.hasSurvivalPressure(), "high incoming damage should count as survival pressure");
game.drawChipChoices();
assert(game._chipChoices.some(id => game.draftSurvivalText(game.cardInfo(id)).includes("生存")), "survival pressure draft should include a survival recommendation");
game.bonuses = { missileRack: 1 }; game._chipChoices = []; game._rng = () => 0.999;
game.drawChipChoices();
assert(hasDraftRoute("导弹"), "draft should include an option for the current focused route");
assert(game.draftFocusText(game.cardInfo("bonus:explosivePayload")).includes("路线续构"), "focused route cards should show draft reason text");
game.boss = null;
const bossHunterBaseWeight = game.draftCardWeight("bonus:bossHunter");
game.boss = { dead: false };
assert(game.draftCardWeight("bonus:bossHunter") > bossHunterBaseWeight, "boss counter cards should be weighted higher during bosses");
assert(game.draftBossText(game.cardInfo("bonus:bossHunter")).includes("Boss"), "boss counter cards should show draft reason text");
game.boss = null;
game._endlessEvent = null; game._endlessEventTimer = 0; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
const shieldBreakerBaseWeight = game.draftCardWeight("bonus:shieldBreaker");
game._endlessEvent = shieldWall; game._endlessEventTimer = 10;
assert(game.hasShieldPressure(), "shield wall should count as shield pressure");
assert(game.draftCardWeight("bonus:shieldBreaker") > shieldBreakerBaseWeight, "shield pressure should weight shieldBreaker higher");
game.drawChipChoices();
assert(game._chipChoices.includes("bonus:shieldBreaker"), "shield pressure draft should include shieldBreaker");
assert(game.draftShieldText(game.cardInfo("bonus:shieldBreaker")).includes("破盾"), "shield pressure cards should show counter text");
game._endlessEvent = null; game._endlessEventTimer = 0; game.enemies = []; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
const eliteHunterBaseWeight = game.draftCardWeight("bonus:eliteHunter");
game._endlessEvent = aceHunt; game._endlessEventTimer = 10;
assert(game.hasElitePressure(), "ace hunt should count as elite pressure");
assert(game.draftCardWeight("bonus:eliteHunter") > eliteHunterBaseWeight, "elite pressure should weight eliteHunter higher");
game.drawChipChoices();
assert(game._chipChoices.includes("bonus:eliteHunter"), "elite pressure draft should include eliteHunter");
assert(game.draftEliteText(game.cardInfo("bonus:eliteHunter")).includes("精英"), "elite pressure cards should show counter text");
game.state = "playing"; game._endlessT = CONFIG.powerup.chipMinEndlessTime - 0.01; game._lastChipDraftAt = -Infinity; game._nextChipDraftAt = 0; game._endlessStats = { drafts: 0 };
assert.strictEqual(game.updateChipDraftTimer(), false, "draft timer should wait until the fixed delay");
game._endlessT = CONFIG.powerup.chipMinEndlessTime;
assert.strictEqual(game.updateChipDraftTimer(), true, "draft timer should start a draft at the fixed delay");
assert.strictEqual(game.state, "chipselect", "draft timer should open selection UI");
assert.strictEqual(game._endlessStats.drafts, 1, "timed draft should be counted once");
assert.strictEqual(game._nextChipDraftAt, CONFIG.powerup.chipMinEndlessTime + CONFIG.powerup.chipDraftInterval, "next draft should be one fixed interval later");
game.state = "playing"; game._endlessT = 90; game._lastChipDraftAt = 80; game._nextChipDraftAt = 120; game._pendingBossDraft = false; game._chipDraftReason = ""; game._endlessStats = { drafts: 0 };
assert.strictEqual(game.scheduleBossDraftReward({ x: 100, y: 100, radius: 40 }), true, "boss reward should pull the next draft earlier");
const bossRewardAt = 80 + CONFIG.powerup.chipMinDraftGap;
assert.strictEqual(game._nextChipDraftAt, bossRewardAt, "boss reward should respect the minimum draft gap");
assert.strictEqual(game._pendingBossDraft, true, "boss reward should mark the next draft reason");
game._endlessT = bossRewardAt - 0.01;
assert.strictEqual(game.updateChipDraftTimer(), false, "boss reward draft should still wait for its scheduled time");
game._endlessT = bossRewardAt;
assert.strictEqual(game.updateChipDraftTimer(), true, "boss reward draft should open at its scheduled time");
assert.strictEqual(game.state, "chipselect", "boss reward should open the selection UI");
assert(game._chipDraftReason.includes("Boss"), "boss reward draft should show a boss reward reason");
assert.strictEqual(game._pendingBossDraft, false, "boss reward marker should clear after opening");
assert.strictEqual(game._endlessStats.bossDrafts, 1, "boss reward should be tracked once");
game.state = "playing"; game._endlessT = 100; game._lastChipDraftAt = 96; game._nextChipDraftAt = 108; game._pendingBossDraft = false; game._endlessStats = {};
assert.strictEqual(game.scheduleBossDraftReward({ x: 100, y: 100, radius: 40 }), false, "boss reward should not make drafts too frequent");
assert.strictEqual(game._nextChipDraftAt, 108, "nearby scheduled draft should be kept");
game.state = "playing"; game._endlessT = 100; game._lastChipDraftAt = 96; game._nextChipDraftAt = 100; game._pendingBossDraft = false; game._endlessStats = { drafts: 0 };
assert.strictEqual(game.updateChipDraftTimer(), false, "draft timer should enforce the minimum draft gap");
game._endlessT = 96 + CONFIG.powerup.chipMinDraftGap;
assert.strictEqual(game.updateChipDraftTimer(), true, "draft timer should open after the minimum draft gap");
for (const e of CONFIG.endless.events.filter(e => e.routeBias)) {
  const matching = draftIds.filter(id => game.draftCardRoute(game.cardInfo(id)) === e.routeBias);
  assert(matching.length, `event ${e.key} routeBias ${e.routeBias} has no matching draft cards`);
  game.endless = true; game._endlessEvent = e; game._endlessEventTimer = 10; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
  game.drawChipChoices();
  assert(game._chipChoices.some(id => matching.includes(id)), `event ${e.key} draft should include one matching route card`);
  assert(game._chipChoices.some(id => id.startsWith("bonus:")), `event ${e.key} draft should include one permanent bonus option`);
  assert(hasSurvivalDraft(), `event ${e.key} draft should include one survival/HP option`);
  assert(hasHpDraft(), `event ${e.key} draft should include one HP/sustain option`);
  assert(hasMaxHpDraft(), `event ${e.key} draft should include one max HP growth option`);
}

const affixes = CONFIG.endless.boss.affixes;
unique(affixes.map(a => a.key), "boss affixes");
assert(affixes.some(a => a.key === "ewar"), "boss affixes should include electronic warfare pressure");
assert(affixes.some(a => a.key === "exposedCore"), "boss affixes should include weak point windows");
assert(affixes.some(a => a.key === "shieldEscort"), "boss affixes should include shield escort pressure");
assert(affixes.some(a => a.key === "phantomEscort"), "boss affixes should include phantom escort pressure");
assert(affixes.some(a => a.key === "swarmEscort"), "boss affixes should include swarm add pressure");
assert(affixes.some(a => a.key === "aceEscort"), "boss affixes should include elite ace pressure");
const shieldEscort = affixes.find(a => a.key === "shieldEscort");
game._endlessEvent = null; game._endlessEventTimer = 0; game.boss = { dead: false, affix: shieldEscort }; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
assert(game.hasShieldPressure(), "shield escort boss should count as shield pressure");
game.drawChipChoices();
assert(game._chipChoices.includes("bonus:shieldBreaker"), "shield escort boss draft should include shieldBreaker");
game.boss = null;
const aceEscort = affixes.find(a => a.key === "aceEscort");
assert.strictEqual(aceEscort.enemy, "gunner", "ace escort should spawn durable gunners");
assert(aceEscort.elite, "ace escort should spawn elite adds");
game._endlessEvent = null; game._endlessEventTimer = 0; game.enemies = []; game.boss = { dead: false, affix: aceEscort }; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
assert(game.hasElitePressure(), "ace escort boss should count as elite pressure");
game.drawChipChoices();
assert(game._chipChoices.includes("bonus:eliteHunter"), "ace escort boss draft should include eliteHunter");
const recentAffixKeys = affixes.slice(0, 2).map(a => a.key);
game._endlessRecentBossAffixes = recentAffixKeys.slice(); game._rng = () => 0;
const pickedAffix = game.pickEndlessBossAffix(affixes);
assert(!recentAffixKeys.includes(pickedAffix.key), "boss affix picker should avoid recent repeats when possible");
for (const a of affixes) {
  assert(a.name && a.desc, `boss affix ${a.key} needs readable text`);
  if (a.scoreMult) between(a.scoreMult, 1, 1.35, `boss affix ${a.key} scoreMult`);
  if (a.attack) {
    assert(["laser", "ring", "escort", "repair", "weak"].includes(a.attack), `boss affix ${a.key} has unknown attack ${a.attack}`);
    between(a.every || 0, 3, 12, `boss affix ${a.key} interval`);
  }
  if (a.count) between(a.count, 6, 24, `boss affix ${a.key} count`);
  if (a.speed) between(a.speed, 140, 360, `boss affix ${a.key} speed`);
  if (a.damageMult) between(a.damageMult, 0.5, 1.2, `boss affix ${a.key} damageMult`);
  if (a.maxAdds) between(a.maxAdds, 1, 6, `boss affix ${a.key} maxAdds`);
  if (a.adds) between(a.adds, 1, 4, `boss affix ${a.key} adds`);
  if (a.enemy) assert(enemyKeys.has(a.enemy), `boss affix ${a.key} references missing enemy ${a.enemy}`);
  if (a.elite) assert(eliteTypes.includes(a.elite), `boss affix ${a.key} references missing elite ${a.elite}`);
  if (a.healPct) between(a.healPct, 0.01, 0.06, `boss affix ${a.key} healPct`);
  if (a.weakDamageMult) between(a.weakDamageMult, 0.15, 0.7, `boss affix ${a.key} weakDamageMult`);
}
const exposedCore = affixes.find(a => a.key === "exposedCore");
game.player = { hp: 100, maxHp: 100, shieldHp: 0 }; game.bonuses = {};
game.boss = { isBoss: true, hp: 100, maxHp: 100, affix: exposedCore, _weakTimer: exposedCore.dur };
assert(game.playerDamage(100, game.boss) > 100, "exposedCore should increase boss damage during weak window");
const weakDamage = game.playerDamage(100, game.boss);
game.bonuses = { weakScanner: 1 };
assert(game.playerDamage(100, game.boss) > weakDamage, "weakScanner should increase weak window damage");
game.floats = []; game.boss = { isBoss: true, x: 100, y: 100, radius: 40, hp: 100, maxHp: 100, affix: exposedCore, _weakTimer: 0 };
game.openBossWeakPoint(game.boss, exposedCore);
assert(game.boss._weakTimer > exposedCore.dur, "weakScanner should extend weak window duration");
game.bonuses = {}; game.enemyBullets = [{ dead: false }]; game.lasers = [{ dead: false }]; game.powerups = []; game.floats = []; game.player = { power: CONFIG.powerup.chipMinPower };
const phaseBoss = { isBoss: true, x: 100, y: 120, radius: 40, hp: 100, maxHp: 100, _fireTimer: 0, def: { name: "PhaseTest", colors: ["#fff", "#ffd43b"], enterY: 120 } };
game.onBossPhaseChange(phaseBoss, 1);
assert(phaseBoss._weakTimer >= CONFIG.bossPhase.weakDuration, "boss phase change should open a weak window");
assert.strictEqual(phaseBoss._weakDamageMult, CONFIG.bossPhase.weakDamageMult, "boss phase weak window should use configured damage");
assert(game.playerDamage(100, phaseBoss) > 100, "boss phase weak window should increase damage");
assert(game.bossAffixHUDText(phaseBoss).includes("破甲"), "boss phase weak window should show HUD text without affix");
const phantomEscort = affixes.find(a => a.key === "phantomEscort");
game.enemies = []; game.floats = []; game.boss = { x: 220, y: 120, radius: 50 };
game.spawnBossEscort(game.boss, phantomEscort);
assert(game.enemies.some(e => e.type === "phantom"), "phantomEscort should spawn phantom adds");
const swarmEscort = affixes.find(a => a.key === "swarmEscort");
game.enemies = []; game.floats = []; game.boss = { x: 220, y: 120, radius: 50 };
assert.strictEqual(game.spawnBossEscort(game.boss, swarmEscort), swarmEscort.adds, "swarmEscort should spawn multiple adds");
assert.strictEqual(game.enemies.filter(e => e.type === "small").length, swarmEscort.adds, "swarmEscort should spawn small swarm adds");
game.enemies = []; game.floats = []; game.boss = { x: 220, y: 120, radius: 50 };
game.spawnBossEscort(game.boss, aceEscort);
assert(game.enemies.some(e => e.type === "gunner" && e.elite === aceEscort.elite), "aceEscort should spawn elite gunner adds");
game.floats = []; game._endlessBossAffixesSeen = []; game._endlessRecentBossAffixes = [];
game.applyEndlessBossAffix({ x: 100, radius: 40, hp: 100, maxHp: 100, score: 100, _fireScale: 1, def: { name: "Test", enterY: 120 } }, phantomEscort);
assert.strictEqual(game._endlessRecentBossAffixes[0], phantomEscort.key, "applied boss affix should be remembered");

const bonusKeys = new Set(Object.keys(CONFIG.bonuses));
for (const key of CONFIG.bonusOrder) assert(bonusKeys.has(key), `bonusOrder references missing bonus ${key}`);
for (const key of ["maxHp", "reinforcedHull", "armorPlating", "fieldRepair", "repairLoop", "repairPulse", "leech", "livingArmor", "medicalReservoir", "painConverter", "armorCaliber", "vitalReactor", "stableFire", "perfectLine", "shieldAmplifier", "shieldBreaker", "signalFilter"]) {
  assert(bonusKeys.has(key), `missing survival/build bonus ${key}`);
}
assert(bonusKeys.has("eliteHunter"), "missing elite counter build bonus");
assert(CONFIG.bonuses.armorCaliber.hpPerDamage > 0, "armorCaliber hpPerDamage must be positive");
between(CONFIG.bonuses.armorCaliber.maxDamage, 2, 8, "armorCaliber maxDamage");
assert(CONFIG.bonuses.vitalReactor.hpPerDamageMult > 0, "vitalReactor hpPerDamageMult must be positive");
between(CONFIG.bonuses.vitalReactor.damageMult, 0.02, 0.08, "vitalReactor damageMult");
between(CONFIG.bonuses.vitalReactor.maxDamageMult, 0.1, 0.4, "vitalReactor maxDamageMult");
between(CONFIG.bonuses.stableFire.hpThreshold, 0.55, 0.85, "stableFire hpThreshold");
between(CONFIG.bonuses.stableFire.damageMult, 0.08, 0.3, "stableFire damageMult");
between(CONFIG.bonuses.perfectLine.delay, 5, 12, "perfectLine delay");
between(CONFIG.bonuses.perfectLine.damageMult, 0.08, 0.25, "perfectLine damageMult");
between(CONFIG.bonuses.perfectLine.cooldownMult, 0.04, 0.16, "perfectLine cooldownMult");
between(CONFIG.bonuses.shieldAmplifier.damageMult, 0.08, 0.3, "shieldAmplifier damageMult");
between(CONFIG.bonuses.shieldBreaker.shieldDamageMult, 0.25, 1.0, "shieldBreaker shieldDamageMult");
between(CONFIG.bonuses.shieldBreaker.breakDamage, 3, 14, "shieldBreaker breakDamage");
between(CONFIG.bonuses.shieldBreaker.range, 100, 220, "shieldBreaker range");
between(CONFIG.bonuses.signalFilter.jamResist, 0.08, 0.3, "signalFilter jamResist");
between(CONFIG.bonuses.eliteHunter.eliteDamageMult, 0.15, 0.6, "eliteHunter eliteDamageMult");
between(CONFIG.bonuses.repairLoop.every, 8, 22, "repairLoop interval");
between(CONFIG.bonuses.repairLoop.healPct, 0.03, 0.12, "repairLoop healPct");
between(CONFIG.bonuses.repairLoop.shield, 4, 16, "repairLoop shield");
between(CONFIG.bonuses.repairPulse.damage, 4, 14, "repairPulse damage");
between(CONFIG.bonuses.repairPulse.range, 120, 220, "repairPulse range");
assert(bonusKeys.has("weakScanner"), "missing weak window build bonus");
between(CONFIG.bonuses.weakScanner.weakDamageMult, 0.1, 0.5, "weakScanner weakDamageMult");
between(CONFIG.bonuses.weakScanner.weakDuration, 0.2, 1.2, "weakScanner weakDuration");
between(CONFIG.bonuses.livingArmor.every, 8, 18, "livingArmor kill interval");
between(CONFIG.bonuses.livingArmor.hp, 1, 6, "livingArmor hp gain");
between(CONFIG.bonuses.livingArmor.maxHp, 18, 60, "livingArmor max HP per stack");
between(CONFIG.bonuses.medicalReservoir.hp, 1, 5, "medicalReservoir hp gain");
between(CONFIG.bonuses.medicalReservoir.maxHp, 12, 50, "medicalReservoir max HP per stack");
game.bonuses = {}; game._bonusStats = {}; game._bonusHpGain = {}; game.floats = []; game.player = { x: 100, y: 100, hp: 80, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
game.activateBonus("maxHp");
game.activateBonus("reinforcedHull");
assert(game._bonusHpGain.maxHp >= CONFIG.bonuses.maxHp.hp, "maxHp bonus should record HP gain");
assert(game._bonusHpGain.reinforcedHull > 0, "reinforcedHull should record HP gain");
assert(game.bonusHUDText("maxHp").includes("HP"), "HP bonus HUD should show gained HP");
assert(game.endlessReviewTags({ telemetry: {}, time: 60, bonuses: game.bonuses, bonusHpGain: game._bonusHpGain }).some(t => t.includes("HP")), "endless review should tag HP builds");
game.bonuses = { livingArmor: 1 }; game._bonusHpGain = {}; game.floats = []; game._bonusKillN = CONFIG.bonuses.livingArmor.every - 1; game.player = { x: 100, y: 100, hp: 80, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.triggerLivingArmorGrowth(), 0, "livingArmor should wait for its kill interval");
game._bonusKillN++;
assert.strictEqual(game.triggerLivingArmorGrowth(), CONFIG.bonuses.livingArmor.hp, "livingArmor should grow max HP on interval kills");
assert(game.player.maxHp > 100 && game._bonusHpGain.livingArmor > 0, "livingArmor should record gained max HP");
game._bonusHpGain.livingArmor = CONFIG.bonuses.livingArmor.maxHp;
game._bonusKillN += CONFIG.bonuses.livingArmor.every;
assert.strictEqual(game.triggerLivingArmorGrowth(), 0, "livingArmor should respect max HP cap");
game.score = 0; game.threat = 0; game._maxThreatLevel = 0; game.bonuses = { medicalReservoir: 1 }; game._bonusHpGain = {}; game.floats = []; game.enemies = []; game.chips = {};
game.player = { x: 100, y: 100, hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0, grantShield(n, dur) { this.shieldHp = n; this.shieldTimer = dur; } };
game.collectPowerup("heal");
assert.strictEqual(game.player.maxHp, 100 + CONFIG.bonuses.medicalReservoir.hp, "medicalReservoir should grow max HP from full HP heals");
assert.strictEqual(game._bonusHpGain.medicalReservoir, CONFIG.bonuses.medicalReservoir.hp, "medicalReservoir should record gained HP");
assert(game.player.shieldHp > 0, "medicalReservoir should keep the normal full HP shield reward");
assert(game.bonusHUDText("medicalReservoir").includes("HP"), "medicalReservoir HUD should show gained HP");
assert(game.draftStatPreviewText(game.cardInfo("bonus:medicalReservoir")).includes("HP"), "medicalReservoir draft preview should show HP cap");
game._bonusHpGain.medicalReservoir = CONFIG.bonuses.medicalReservoir.maxHp; const cappedHp = game.player.maxHp;
game.collectPowerup("heal");
assert.strictEqual(game.player.maxHp, cappedHp, "medicalReservoir should respect max HP cap");
const repairLoop = CONFIG.bonuses.repairLoop;
game.bonuses = { repairLoop: 1 }; game.chips = {}; game.combo = 0; game.threat = 0; game._maxThreatLevel = 0; game._noHitT = 0; game._fieldRepairT = 0; game._repairLoopT = repairLoop.every - 0.01; game.floats = [];
game.player = { x: 100, y: 100, hp: 70, maxHp: 100, power: 1, overcharge: 0, shieldHp: 0, heal(n) { this.hp = Math.min(this.maxHp, this.hp + n); }, grantShield(n, dur) { this.shieldHp = n; this.shieldTimer = dur; } };
game.updateDepthSystems(0.02);
assert(game.player.hp > 70, "repairLoop should heal on interval");
game._repairLoopT = repairLoop.every; game.player.hp = game.player.maxHp; game.player.shieldHp = 0;
game.updateDepthSystems(0);
assert(game.player.shieldHp > 0, "repairLoop should grant shield at full HP");
assert(game.draftStatPreviewText(game.cardInfo("bonus:repairLoop")).includes("%"), "repairLoop draft preview should show healing");
game.bonuses = { repairPulse: 1 }; game.floats = []; game.shockwaves = []; game.enemies = [{ dead: false, x: 115, y: 100, radius: 10, hp: 20, maxHp: 20, damage(d) { this.hp -= d; if (this.hp <= 0) { this.dead = true; return true; } return false; } }];
game.player = { x: 100, y: 100, hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.triggerRepairPulse(game.player), 1, "repairPulse should hit nearby enemies");
assert(game.enemies[0].hp < 20 && game.shockwaves.length, "repairPulse should deal damage and show feedback");
assert(game.draftStatPreviewText(game.cardInfo("bonus:repairPulse")).includes("→"), "repairPulse draft preview should show damage gain");
game.bonuses = { shieldAmplifier: 1 }; game.chips = {}; game.player = { hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.playerDamage(100), 100, "shieldAmplifier should not add damage without shield");
game.player.shieldHp = 10;
assert(game.playerDamage(100) > 100, "shieldAmplifier should add damage while shielded");
game.bonuses = { eliteHunter: 1 }; game.chips = {}; game.player = { hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.playerDamage(100, { hp: 100, maxHp: 100 }), 100, "eliteHunter should not add damage to normal enemies");
assert(game.playerDamage(100, { elite: "shield", hp: 100, maxHp: 100 }) > 100, "eliteHunter should add damage to elite enemies");
assert(game.draftStatPreviewText(game.cardInfo("bonus:eliteHunter")).includes("%"), "eliteHunter draft preview should show damage");
assert(game.bonusHUDText("eliteHunter").includes("%"), "eliteHunter HUD should show elite damage");
game.bonuses = { stableFire: 1 }; game.chips = {}; game.player = { hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert(game.playerDamage(100) > 100, "stableFire should add damage while HP is high");
assert(game.draftStatPreviewText(game.cardInfo("bonus:stableFire")).includes("%"), "stableFire draft preview should show damage");
assert(game.bonusHUDText("stableFire").includes("激活"), "stableFire HUD should show active state");
game.player.hp = 40;
assert.strictEqual(game.stableFireDamageMult(), 0, "stableFire should turn off at low HP");
assert(game.bonusHUDText("stableFire").includes("待机"), "stableFire HUD should show inactive state");
game.bonuses = { perfectLine: 1 }; game.chips = {}; game.enemies = []; game.boss = null; game._noHitT = CONFIG.bonuses.perfectLine.delay - 0.01; game.player = { x: 100, y: 100, hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.playerDamage(100), 100, "perfectLine should wait for no-hit delay");
assert.strictEqual(game.perfectLineValue("cooldownMult"), 0, "perfectLine cooldown should wait for no-hit delay");
assert(game.bonusHUDText("perfectLine").includes("s"), "perfectLine HUD should show pending timer");
game._noHitT = CONFIG.bonuses.perfectLine.delay;
assert(game.playerDamage(100) > 100, "perfectLine should add damage after no-hit delay");
assert(game.weaponCooldownMult() < 1, "perfectLine should speed weapons after no-hit delay");
assert(game.draftStatPreviewText(game.cardInfo("bonus:perfectLine")).includes("%"), "perfectLine draft preview should show gains");
assert(game.bonusHUDText("perfectLine").includes("%"), "perfectLine HUD should show active state");
game.endless = false; game.currentLevel = 1; game._rng = () => 0.999; game.bonuses = { shieldBreaker: 1 }; game.chips = {}; game.floats = []; game.shockwaves = [];
const shielded = new Enemy("shieldCarrier", 100, 0, "straight"); shielded.y = 100;
const splashTarget = { dead: false, x: 130, y: 100, radius: 12, hp: 30, maxHp: 30, damage(d) { this.hp -= d; if (this.hp <= 0) { this.dead = true; return true; } return false; } };
game.enemies = [shielded, splashTarget];
shielded.damage(CONFIG.enemy.shieldCarrier.shield / (1 + CONFIG.bonuses.shieldBreaker.shieldDamageMult));
assert(shielded.eliteShield <= 0, "shieldBreaker should break shields faster");
assert(game.shockwaves.length && game.floats.some(f => f.text.includes("破盾")), "shieldBreaker should show break feedback");
assert(splashTarget.hp < 30, "shieldBreaker should shock nearby enemies on break");
assert(game.draftStatPreviewText(game.cardInfo("bonus:shieldBreaker")).includes("%"), "shieldBreaker draft preview should show shield damage");
assert(game.bonusHUDText("shieldBreaker").includes("%"), "shieldBreaker HUD should show shield damage");
between(CONFIG.bonuses.painConverter.energyPerHp, 0.5, 2, "painConverter energyPerHp");
between(CONFIG.bonuses.painConverter.maxEnergy, 15, 60, "painConverter maxEnergy");
between(CONFIG.bonuses.comboBarrage.count, 1, 4, "comboBarrage count");
between(CONFIG.bonuses.comboBarrage.maxCount, 4, 12, "comboBarrage maxCount");
between(CONFIG.bonuses.sideCannons.maxPairs, 1, 4, "sideCannons maxPairs");
between(CONFIG.bonuses.laserSplitter.maxPairs, 1, 5, "laserSplitter maxPairs");
between(CONFIG.bonuses.clusterWarheads.maxCount, CONFIG.bonuses.clusterWarheads.count, 8, "clusterWarheads maxCount");
game.bonuses = { comboBarrage: 1 }; game.homingShots = []; game.floats = []; game.player = { x: 100, y: 100, radius: 15, overcharge: 0 };
game.comboMilestone(10);
assert.strictEqual(game.homingShots.length, CONFIG.bonuses.comboBarrage.count, "comboBarrage should fire homing shots on combo milestone");
assert(game.draftStatPreviewText(game.cardInfo("bonus:comboBarrage")).includes("2"), "comboBarrage draft preview should show shot count");
game.bonuses = {}; assert.strictEqual(game.missileVolleyBonus(), 0, "missile route should not add volley before ready");
game.bonuses = { missileRack: 3 }; assert.strictEqual(game.missileVolleyBonus(), 1, "missile route should add one missile when ready");
assert(game.routeEffectText().includes("导弹+1"), "missile route resonance text should show the extra missile");
game.bonuses = {}; const baseMissile = new Missile(100, 100, 0);
game.bonuses = { missileRack: 3 }; const routeMissile = new Missile(100, 100, 0);
assert(routeMissile.damage > baseMissile.damage && routeMissile.splash > baseMissile.splash, "missile route should increase missile damage and splash");
game.bonuses = {}; const baseLaser = new PlayerLaser(100, 100, 0);
game.bonuses = { laserLens: 3 }; const routeLaser = new PlayerLaser(100, 100, 0);
assert(routeLaser.damage > baseLaser.damage && routeLaser.life > baseLaser.life, "laser route should increase laser damage and duration");
game.bonuses = {}; assert.strictEqual(game.homingVolleyBonus(), 0, "homing route should not add shots before ready");
game.bonuses = { swarmCore: 3 }; assert.strictEqual(game.homingVolleyBonus(), 1, "homing route should add one homing shot when ready");
assert(game.homingCooldownMult() < 1 && game.routeEffectText().includes("追踪+1"), "homing route should speed up and show resonance text");
game.bonuses = { missileRack: 2 };
assert(game.routeProgressText().includes("/7"), "route progress should show resonance threshold");
assert(game.routePreviewText(game.cardInfo("bonus:missileRack")).includes("解锁共鸣"), "draft route preview should show resonance unlock");

console.log(`balance check passed: ${CONFIG.endless.events.length} events, ${affixes.length} boss affixes, ${CONFIG.bonusOrder.length} bonuses`);
