"use strict";

const fs = require("fs");
const vm = require("vm");
const assert = require("assert");

const sandbox = { console, Math };
sandbox.Settings = { data: { controlMode: "touch" } };
sandbox.input = { targetX: 270, targetY: 800, joyDX: 0, joyDY: 0 };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync("src/config.js", "utf8") + "\nglobalThis.CONFIG = CONFIG;", sandbox);
vm.runInContext(fs.readFileSync("src/core.js", "utf8"), sandbox);
vm.runInContext(fs.readFileSync("src/game.js", "utf8") + "\nglobalThis.game = game;", sandbox);
const { CONFIG } = sandbox;
const { game } = sandbox;
sandbox.FloatText = class FloatText { constructor(x, y, text, color) { this.x = x; this.y = y; this.text = text; this.color = color; } };
sandbox.Shockwave = class Shockwave { constructor(x, y, maxR, color) { this.x = x; this.y = y; this.maxR = maxR; this.color = color; } };
sandbox.pools = {
  enemy: { get(type, x, y, move, elite) { const cfg = CONFIG.enemy[type], r = cfg.radius; return { type, x, y: cfg.fromBottom ? CONFIG.HEIGHT + r + y : y, move: cfg.move || move, elite, dead: false, isBoss: false, radius: r, cfg }; } },
  enemyBullet: { get(x, y, vx, vy, damage, opts) { return { x, y, vx, vy, damage, dead: false, kind: opts && opts.kind || "", radius: opts && opts.radius || CONFIG.enemyBullet.radius }; } },
  homingShot: { get(x, y, overcharge) { return { x, y, overcharge }; } },
};
sandbox.Sound = { powerup() {}, tone() {}, laser() {} };
sandbox.Haptics = { powerup() {} };
vm.runInContext(fs.readFileSync("src/entities.js", "utf8") + "\nglobalThis.Player = Player; globalThis.Enemy = Enemy; globalThis.EnemyBullet = EnemyBullet; globalThis.Missile = Missile; globalThis.PlayerLaser = PlayerLaser; globalThis.Boss = Boss; globalThis.runBossAttack = runBossAttack;", sandbox);
const { Player, Enemy, EnemyBullet, Missile, PlayerLaser, Boss, runBossAttack } = sandbox;

const between = (value, min, max, label) => assert(value >= min && value <= max, `${label} ${value} outside ${min}-${max}`);
const unique = (items, label) => assert.strictEqual(new Set(items).size, items.length, `${label} has duplicate keys`);
const approx = (value, target, eps, label) => assert(Math.abs(value - target) <= eps, `${label} ${value} outside ${target} +/- ${eps}`);
const focusedDps = { earlyFull: 88, fourPick: 153, strongRoute: 1075, nearCap: 2700, lateBossSustain: 3000 };

assert(CONFIG && CONFIG.player && CONFIG.endless, "CONFIG did not load");
assert.strictEqual(CONFIG.player.maxPower, 8, "player max power should allow one more late-game tier");
assert.strictEqual(CONFIG.player.maxOvercharge, 8, "player overcharge cap should allow longer endless scaling");
assert.strictEqual(CONFIG.wingMax, 5, "wing cap should allow stronger endless scaling");
assert(CONFIG.weapon[CONFIG.player.maxPower], "maxPower should have a weapon pattern");
assert.strictEqual(CONFIG.challenge.rulesVersion, 88, "challenge rules should bump for five-minute hell scaling");
assert(CONFIG.endlessDifficulties && CONFIG.endlessDifficulties.normal && CONFIG.endlessDifficulties.hell, "endless difficulties should define normal and hell");
assert(CONFIG.endlessDifficulties.normal.enemyHpMult < CONFIG.endlessDifficulties.hell.enemyHpMult, "normal endless enemies should have less HP than hell");
assert(CONFIG.endlessDifficulties.normal.bossHpMult < CONFIG.endlessDifficulties.hell.bossHpMult, "normal endless bosses should have less HP than hell");
assert(CONFIG.endlessDifficulties.normal.enemyHpDoubleInterval > CONFIG.endlessDifficulties.hell.enemyHpDoubleInterval, "normal endless enemy HP curve should grow slower than hell");
assert(CONFIG.endlessDifficulties.normal.dmgDoubleInterval > CONFIG.endless.dmgDoubleInterval, "normal endless bullet damage curve should grow slower than hell");
assert(CONFIG.endlessDifficulties.hell.playerHpMult > 1 && CONFIG.endlessDifficulties.hell.playerDmgMult > 1, "hell should grant strong player buffs");
assert.strictEqual(CONFIG.endlessDifficulties.hell.playerDmgMult, 4, "hell player damage should be doubled again");
assert.strictEqual(CONFIG.endlessDifficulties.hell.bossHpMult, 5, "hell endless boss HP should use 5x configured HP");
assert.strictEqual(CONFIG.endlessDifficulties.hell.bossInvulnDuration, 5, "hell endless boss invulnerability should last 5s");
assert(CONFIG.endlessDifficulties.hell.bossBulletMult > 1, "hell endless bosses should add more bullets");
assert(CONFIG.endlessDifficulties.hell.startWings > 0 && CONFIG.endlessDifficulties.hell.startPower > 0, "hell should grant starting wings and power");
assert.strictEqual(CONFIG.endlessDifficulties.normal.playerDmgMult, 3, "normal should grant 3x player damage");
assert.strictEqual(CONFIG.endlessDifficulties.normal.enemyHpMult, 0.40, "normal endless enemy HP should be lower");
assert.strictEqual(CONFIG.endlessDifficulties.normal.bossHpMult, 0.52, "normal endless boss HP should be lower");
assert.strictEqual(CONFIG.endlessDifficulties.normal.enemyHpBoostMult, 1.30, "normal endless 60s HP boost should be lower");
assert.strictEqual(CONFIG.endlessDifficulties.normal.enemyHpDoubleInterval, 360, "normal endless enemy HP should grow slower");
assert.strictEqual(CONFIG.endlessDifficulties.normal.startingDrafts, 2, "normal should start with 2 immediate drafts");
assert.strictEqual(CONFIG.endlessDifficulties.hell.startingDrafts, 3, "hell should start with 3 immediate drafts");
assert.strictEqual(CONFIG.endlessDifficulties.normal.draftInterval, 30, "normal follow-up drafts should use 30s cadence");
assert.strictEqual(CONFIG.endlessDifficulties.hell.draftInterval, 30, "hell follow-up drafts should use 30s cadence");

between(CONFIG.powerup.chipMinEndlessTime, 15, 30, "first endless draft delay");
between(CONFIG.powerup.chipDraftInterval, 15, 30, "endless draft interval");
between(CONFIG.powerup.chipBossDraftDelay, 15, 30, "boss draft delay");
between(CONFIG.powerup.chipMinDraftGap, 15, 30, "minimum endless draft gap");
assert.strictEqual(CONFIG.powerup.chipMinEndlessTime, 30, "first timed endless draft should wait 30s");
assert.strictEqual(CONFIG.powerup.chipDraftInterval, 30, "endless draft interval should be 30s");
assert.strictEqual(CONFIG.powerup.chipBossDraftDelay, 30, "boss draft delay should be 30s");
assert.strictEqual(CONFIG.powerup.chipMinDraftGap, 30, "minimum endless draft gap should be 30s");
assert.strictEqual(CONFIG.powerup.dropChance, 0.11, "normal powerup drops should be toned down");
between(CONFIG.endless.maxEnemies, 8, 20, "endless max enemies");
between(CONFIG.endless.startingDrafts, 1, 3, "endless starting drafts");
assert.strictEqual(CONFIG.endless.startingDrafts, 2, "endless challenge should start with 2 drafts");
assert.strictEqual(CONFIG.endless.powerupChance, 0.09, "endless powerup chance should be toned down");
between(CONFIG.endless.enemyHpBaseMult, 1.1, 2.0, "endless enemy base HP");
assert.strictEqual(CONFIG.endless.enemyHpBaseMult, 1.15, "endless enemy base HP should not make opening mobs spongy");
assert.strictEqual(CONFIG.endless.enemyHpBoostTime, 60, "endless enemies should jump to the target boost at 60s");
assert.strictEqual(CONFIG.endless.enemyHpBoostMult, 1.8, "endless enemies should use a lower 60s HP boost");
assert.strictEqual(CONFIG.endless.enemyHpDoubleInterval, 240, "endless enemy HP multiplier should grow without creating a wall");
assert.strictEqual(CONFIG.endless.enemyHpFloorTime, 35, "endless enemies should gain a DPS-based HP floor after the opening wave");
assert.strictEqual(CONFIG.endless.enemyHpFloor, 170, "opening enemy HP floor should avoid outpacing player growth");
assert.strictEqual(CONFIG.endless.enemyHpFloorTargetTime, 200, "endless enemies should enter ten-thousand HP territory around 200s");
assert.strictEqual(CONFIG.endless.enemyHpFloorTarget, 5600, "200s enemy HP floor should let strong routes clear mobs");
assert.strictEqual(CONFIG.endless.enemyHpFloorMax, 22000, "late enemy HP floor should leave room for post-5m pressure");
assert.strictEqual(CONFIG.endless.enemyHpLateTime, 300, "endless adaptive pressure should start after 5 minutes");
assert.strictEqual(CONFIG.endless.dynamicHp.startTime, 300, "dynamic HP calibration should start after 5 minutes");
assert.strictEqual(CONFIG.endless.dynamicHp.interval, 60, "dynamic HP calibration should run once per minute");
assert.strictEqual(CONFIG.endless.dynamicHp.bossDamageReduction, 0.5, "dynamic hell bosses should have 50% DR");
assert.strictEqual(CONFIG.endless.dynamicHp.enemyDamageReduction, 0.2, "dynamic hell enemies should have 20% DR");
between(CONFIG.endless.dmgRampMult, 1.5, 3.5, "endless damage ramp");
between(CONFIG.endless.boss.firstDelay, 20, 45, "first boss delay");
between(CONFIG.endless.boss.interval, 25, 55, "boss interval");
assert.strictEqual(CONFIG.endless.boss.baseHpMult, 1, "first endless boss should keep base HP");
assert.strictEqual(CONFIG.endless.boss.secondHpMult, 5, "second endless boss should be 5x base HP");
assert.strictEqual(CONFIG.endless.boss.hpGrowthMult, 2, "later endless bosses should double from the second boss");
assert.strictEqual(CONFIG.endless.boss.hpGrowthMax, 80, "late endless boss HP should cap after the 80x tier");
assert.strictEqual(CONFIG.endless.boss.drStart, 0.10, "second endless boss should start at 10% DR");
assert.strictEqual(CONFIG.endless.boss.drStep, 0.05, "endless boss DR should step by 5%");
assert.strictEqual(CONFIG.endless.boss.drMax, 0.30, "endless boss DR should cap at 30%");
between(CONFIG.bossPhase.weakDuration, 1.5, 4, "boss phase weak duration");
between(CONFIG.bossPhase.weakDamageMult, 0.1, 0.45, "boss phase weak damage");
between(CONFIG.bossInvuln.minCount, 2, 3, "boss invuln min count");
between(CONFIG.bossInvuln.maxCount, 2, 3, "boss invuln max count");
between(CONFIG.bossInvuln.minDuration, 5, 10, "boss invuln min duration");
between(CONFIG.bossInvuln.maxDuration, 5, 10, "boss invuln max duration");
between(CONFIG.endless.eventClearScore, 300, 1800, "event clear score");
assert.strictEqual(CONFIG.endless.eventClearScore, 700, "event clear score should be toned down");
between(CONFIG.endless.eventCleanShield, 8, 50, "event clean shield");
assert.strictEqual(CONFIG.endless.eventCleanShield, 18, "clean event shield should be toned down");
between(CONFIG.endless.eventCleanShieldDur, 2, 10, "event clean shield duration");
assert.strictEqual(CONFIG.chips.laserFocus.duration, 15, "laserFocus chip should last long enough to feel impactful");
assert.strictEqual(CONFIG.chips.laserFocus.laserDamageBonus, 2, "laserFocus chip should provide visible laser growth");
assert.strictEqual(CONFIG.chips.homingSwarm.damageBonus, 2, "homingSwarm chip should provide visible homing growth");
assert.strictEqual(CONFIG.chips.missileBarrage.damageBonus, 2, "missileBarrage chip should provide visible missile growth");
assert.strictEqual(CONFIG.chips.chargeCore.boostBonus, 4, "chargeCore chip should provide visible charge growth");
assert.strictEqual(CONFIG.chips.capacitor.block, 24, "capacitor chip should provide visible defensive growth");
assert.strictEqual(CONFIG.bonuses.damage.damageMult, 0.12, "damage bonus should be toned down");
assert.strictEqual(CONFIG.bonuses.fireRate.cooldownMult, 0.08, "fireRate bonus should be toned down");
assert.strictEqual(CONFIG.bonuses.perfectLine.damageMult, 0.10, "perfectLine damage should be toned down");
assert.strictEqual(CONFIG.bonuses.bossHunter.bossDamageMult, 0.30, "bossHunter bonus should be toned down");
const pickBuffCards = ["chip:laserFocus", "chip:homingSwarm", "chip:missileBarrage", "chip:chargeCore", "chip:capacitor", "chip:sideGuns", "chip:volatileCore", "bonus:maxHp", "bonus:livingArmor", "bonus:medicalReservoir", "bonus:repairLoop", "bonus:painConverter", "bonus:salvage", "bonus:shieldBreaker", "bonus:missileInterceptor", "bonus:magnetCore", "bonus:comboBattery", "bonus:lastStand", "bonus:emergencyBarrier"];
assert(pickBuffCards.length >= 14, "draft pick buffs should cover more card routes");
for (const id of pickBuffCards) {
  const card = game.cardInfo(id), buff = card && card.pickBuff;
  assert(buff && buff.label, `${id} should show a pick buff label`);
  if (buff.energy) between(buff.energy, 1, 12, `${id} pick energy`);
  if (buff.shield) between(buff.shield, 1, 14, `${id} pick shield`);
  if (buff.healPct) between(buff.healPct, 0.01, 0.08, `${id} pick heal pct`);
  if (buff.clearBullets) between(buff.clearBullets, 100, 180, `${id} pick clear range`);
}
assert(game.draftPickBuffText(game.cardInfo("bonus:missileInterceptor")).includes("附带"), "pick buff should be visible in draft preview");
assert(game.draftPickBuffText(game.cardInfo("bonus:missileInterceptor")).includes("拦截"), "pick buff preview should name the tactical kind");
assert(game.draftPickBuffTag(game.cardInfo("chip:capacitor")).includes("护盾"), "pick buff tag should name shield cards clearly");
assert.strictEqual(game.draftPickBuffKind(game.cardInfo("bonus:comboBattery")), "蓄盾", "mixed energy+shield pick buff should have its own kind");

const enemyKeys = new Set(Object.keys(CONFIG.enemy));
const shieldCarrier = CONFIG.enemy.shieldCarrier;
assert(shieldCarrier, "enemy variety should include shield carrier");
between(shieldCarrier.hp, 10, 30, "shieldCarrier hp");
between(shieldCarrier.shield, 8, 40, "shieldCarrier shield");
between(shieldCarrier.fireInterval, 1.2, 2.8, "shieldCarrier fireInterval");
const kamikaze = CONFIG.enemy.kamikaze;
assert(kamikaze, "enemy variety should include kamikaze");
assert.strictEqual(kamikaze.move, "rearChase", "kamikaze should use rear chase movement");
assert.strictEqual(kamikaze.fromBottom, true, "kamikaze should enter from behind the player");
assert(kamikaze.crashDamage > CONFIG.crashDamage, "kamikaze should hit harder than normal collisions");
assert(CONFIG.moves.rearChase, "rear chase movement should exist");
assert.strictEqual(CONFIG.moves.rearChase.warn, 2, "rear chase should warn for 2 seconds");
assert.strictEqual(CONFIG.moves.rearChase.boost, 2.5, "rear chase should boost for 2.5 seconds");
assert.strictEqual(CONFIG.moves.rearChase.track, 2.5, "rear chase should keep tracking during the 2.5s boost");
assert(Math.abs(CONFIG.enemy.kamikaze.speed * CONFIG.moves.rearChase.boostMul - CONFIG.enemy.small.speed) < 1e-9, "rear chase boost should match the fastest small plane speed");
assert(CONFIG.moves.rearChase.boostMul > CONFIG.moves.rearChase.speedMul, "rear chase boost should be faster than normal chase");
const beacon = CONFIG.enemy.beacon, gunner = CONFIG.enemy.gunner, mineLayer = CONFIG.enemy.mineLayer, tether = CONFIG.enemy.tether;
assert(beacon && gunner && mineLayer && tether, "enemy special types should exist");
between(beacon.homingInterval, 2.8, 5, "beacon homing cadence");
between(gunner.homingInterval, 3.4, 5.5, "gunner homing cadence");
between(beacon.homingTurn, 2, 4, "beacon homing turn");
assert.strictEqual(mineLayer.zoneKind, "fire", "mineLayer should add fire zones in endless");
between(mineLayer.zoneRadius, 32, 70, "fire zone radius");
between(mineLayer.zoneDamage, 2, 7, "fire zone damage");
assert.strictEqual(tether.zoneKind, "ice", "tether should add ice zones in endless");
between(tether.zoneRadius, 36, 72, "ice zone radius");
between(tether.slowMult, 0.35, 0.75, "ice slow multiplier");
const eliteTypes = CONFIG.elite.types || [];
unique(eliteTypes, "elite types");
assert(eliteTypes.length >= 5, "elite type variety should include at least 5 types");
assert(eliteTypes.includes("jammer"), "elite type variety should include jammer");
for (const key of eliteTypes) {
  const e = CONFIG.elite[key];
  assert(e && e.name && e.color, `elite ${key} needs readable text`);
  if (e.hpMult) between(e.hpMult, 0.75, 1.35, `elite ${key} hpMult`);
  if (e.speedMult) between(e.speedMult, 1, 1.45, `elite ${key} speedMult`);
  if (e.fireMult) between(e.fireMult, 0.6, 1, `elite ${key} fireMult`);
  if (e.regenEvery) between(e.regenEvery, 1.5, 4, `elite ${key} regenEvery`);
  if (e.regenPct) between(e.regenPct, 0.03, 0.12, `elite ${key} regenPct`);
  if (e.jamRadius) between(e.jamRadius, 140, 280, `elite ${key} jamRadius`);
  if (e.weaponSlow) between(e.weaponSlow, 1.05, 1.4, `elite ${key} weaponSlow`);
}
game.boss = null; game.enemies = [{ dead: false, x: 100, y: 100, radius: 20, type: "medium", eliteCfg: CONFIG.elite.jammer }];
assert(game.jamFactor(100, 100) > 1, "jammer elite should slow weapons in range");
assert.strictEqual(game.jamFactor(500, 100), 1, "jammer elite should not slow weapons out of range");
const jammedWithoutFilter = game.jamFactor(100, 100);
game.bonuses = { signalFilter: 1 };
assert(game.jamFactor(100, 100) < jammedWithoutFilter, "signalFilter should reduce jammer slow");
game.bonuses = {};
game.endless = true; game.endlessLite = false; game._endlessDiffKey = "normal"; game._endlessT = CONFIG.endless.enemyHpBoostTime; game._endlessEvent = null; game._endlessEventTimer = 0;
const normalHpAtBoost = game.endlessEnemyHpMult();
game._endlessDiffKey = "hell";
const hellHpAtBoost = game.endlessEnemyHpMult();
assert(normalHpAtBoost < hellHpAtBoost, "normal endless HP ramp should stay below hell at boost time");
game._endlessT = CONFIG.endless.dmgRampTime;
game._endlessDiffKey = "normal";
const normalDmgAtRamp = game.endlessBulletDmgMult();
game._endlessDiffKey = "hell";
const hellDmgAtRamp = game.endlessBulletDmgMult();
assert(normalDmgAtRamp < hellDmgAtRamp, "normal endless bullet damage ramp should stay below hell");
game.endless = true; game.endlessLite = false; game._endlessDiffKey = "hell"; game._endlessT = 0; game._endlessEvent = null; game._endlessEventTimer = 0;
assert(game.endlessEnemyHpMult() >= CONFIG.endless.enemyHpBaseMult, "endless enemies should start with the base HP multiplier");
game._endlessT = CONFIG.endless.enemyHpFloorTime;
assert.strictEqual(game.endlessEnemyHpFloor(), 0, "enemy HP floor should ramp in instead of jumping at the opening floor time");
game._endlessT = CONFIG.endless.enemyHpFloorTime + 5;
const hellFloorAt40 = game.endlessEnemyHpFloor();
game._endlessDiffKey = "normal";
const normalFloorAt40 = game.endlessEnemyHpFloor();
assert(normalFloorAt40 < hellFloorAt40, "normal endless HP floor should stay below hell");
between(hellFloorAt40, 3, 12, "40s hell enemy floor should avoid a sudden HP wall");
between(normalFloorAt40, 2, 10, "40s normal enemy floor should avoid a sudden HP wall");
game._endlessDiffKey = "hell";
game._endlessT = CONFIG.endless.enemyHpBoostTime;
assert(Math.abs(game.endlessEnemyHpMult() - CONFIG.endlessDifficulties.hell.enemyHpBoostMult) < 1e-9, "endless enemies should reach the hell HP boost at 60s");
assert.strictEqual(game.endlessEnemyHpFloor(), Math.round(CONFIG.endless.enemyHpFloor * CONFIG.endlessDifficulties.hell.enemyHpMult), "enemy HP floor should reach the scaled opening floor at the HP boost time");
between(game.endlessEnemyHpFloor() / focusedDps.fourPick, 0.55, 1.4, "60s enemy floor TTK");
game._endlessT = CONFIG.endless.enemyHpBoostTime + CONFIG.endless.enemyHpDoubleInterval;
assert(Math.abs(game.endlessEnemyHpMult() - CONFIG.endlessDifficulties.hell.enemyHpBoostMult * 2) < 1e-9, "endless enemies should double from the 60s HP boost");
game._endlessT = CONFIG.endless.enemyHpBoostTime + CONFIG.endless.enemyHpDoubleInterval * 2;
assert(game.endlessEnemyHpMult() > CONFIG.endlessDifficulties.hell.enemyHpBoostMult * 4, "post-5m endless enemies should exceed the old doubled curve");
game._endlessT = CONFIG.endless.enemyHpFloorTargetTime;
assert.strictEqual(game.endlessEnemyHpFloor(), Math.round(CONFIG.endless.enemyHpFloorTarget * CONFIG.endlessDifficulties.hell.enemyHpMult), "200s enemy floor should stay below the old wall");
between(game.endlessEnemyHpFloor() / focusedDps.strongRoute, 3, 4.5, "200s enemy floor TTK for strong focused fire");
game._endlessT = 300;
between(game.endlessEnemyHpFloor(), 4500, CONFIG.endless.enemyHpFloorMax, "300s enemy floor");
between(game.endlessEnemyHpFloor() / focusedDps.nearCap, 1.4, 2.2, "300s enemy floor TTK for near-cap focused fire");
const hpMult300 = game.endlessEnemyHpMult(), floor300 = game.endlessEnemyHpFloor();
game._endlessT = 360;
assert(game.endlessEnemyHpMult() > hpMult300 * 1.45, "post-5m enemy HP multiplier should steepen");
assert(game.endlessEnemyHpFloor() > floor300 * 1.25, "post-5m enemy HP floor should steepen");
between(CONFIG.endless.spawn.countStepMax, 3, 10, "endless spawn count cap");
const cappedSpawnCount = CONFIG.endless.spawn.countBase + CONFIG.endless.spawn.countStepMax;
assert.strictEqual(game.endlessSpawnCount(9999), cappedSpawnCount, "endless spawn count should cap for readability and performance");
assert.deepStrictEqual([0, 1, 2, 3].map(n => game.endlessBossHpMult(n)), [1, 5, 10, 20], "endless boss HP should scale 1x/5x/10x/20x");
assert.deepStrictEqual([0, 1, 2, 3, 4, 5].map(n => game.endlessBossHpMult(n)), [1, 5, 10, 20, 40, 80], "endless boss HP should cap at the 80x tier");
game._endlessDiffKey = "normal";
game._endlessT = CONFIG.endless.dynamicHp.startTime;
for (const n of [0, 1, 2, 3, 8]) approx(game.endlessBossDamageReduction(n), 0, 1e-9, `normal endless boss ${n} DR`);
game._endlessDiffKey = "hell";
game._endlessT = CONFIG.endless.dynamicHp.startTime - 1;
for (const [n, dr] of [[0, 0], [1, 0.1], [2, 0.15], [3, 0.2], [4, 0.25], [8, 0.3]]) approx(game.endlessBossDamageReduction(n), dr, 1e-9, `endless boss ${n} DR`);
game._endlessT = CONFIG.endless.dynamicHp.startTime;
for (const n of [0, 1, 8]) approx(game.endlessBossDamageReduction(n), 0.5, 1e-9, `dynamic hell boss ${n} DR`);
const lateBossEffectiveHp = CONFIG.bosses[9].hp * CONFIG.endlessDifficulties.hell.bossHpMult * game.endlessBossHpMult(8) / (1 - game.endlessBossDamageReduction(8));
between(lateBossEffectiveHp / focusedDps.lateBossSustain + CONFIG.bossInvuln.minCount * CONFIG.endlessDifficulties.hell.bossInvulnDuration, 600, 900, "late boss expected sustain duration");
game.resetEndlessAdaptiveHp(); game._endlessT = 310; game._endlessBossT = -5;
game.recordEndlessBossDeath({ _endlessSpawnT: 280, maxHp: 60000, _endlessDr: 0, _endlessEffectiveHp: 60000 });
assert.strictEqual(game._endlessBossT, CONFIG.endless.dynamicHp.bossMinGap, "short-lived bosses should leave a minimum gap");
assert.strictEqual(game._endlessAdaptiveHp.bossFloor, 240000, "dynamic boss floor should include active DR in effective HP");
assert.strictEqual(game.endlessBossHpFloor(0.5), 120000, "next 50% DR boss should target at least 60s actual HP");
game.player = { x: 220, y: 620 }; game.score = 0; game._endlessStats = { events: 0, eventClears: 0, eventScore: 0 };
game._endlessAdaptiveHp.next = 360; game._endlessT = 360;
for (let i = 0; i < 10; i++) game._endlessAdaptiveHp.enemyLives.push({ t: 360, life: 2 });
game._endlessAdaptiveHp.damage.push({ t: 360, d: 60000 });
game.updateEndlessDynamicHp();
assert(game._endlessAdaptiveHp.enemyFloor >= 2000, "fast-cleared enemies should get a DPS-based 2s HP floor");
assert(game.score >= CONFIG.endless.dynamicHp.score, "dynamic HP calibration should pay a high score bonus");
assert(!("hpStep" in CONFIG.endless.boss), "endless boss HP should not use the old linear growth");
assert(!("hpStepMax" in CONFIG.endless.boss), "endless boss HP should not have a growth cap");
game._endlessT = CONFIG.endless.dmgDoubleInterval || 300;
const bulletAt5m = game.endlessBulletDmgMult();
game._endlessT = (CONFIG.endless.dmgDoubleInterval || 300) * 2;
assert(game.endlessBulletDmgMult() > bulletAt5m, "endless bullet damage should keep growing without a cap");
game.endless = true; game.endlessLite = false; game._endlessDiffKey = "hell"; game._startingDrafts = 2; game._startingDraftsTotal = 3; game._inStartingDraft = true; game.state = "chipselect"; game._endlessT = 0;
game.resumeAfterDraft();
assert.strictEqual(game.state, "chipselect", "hell opening drafts should continue immediately");
assert.strictEqual(game._startingDrafts, 1, "hell opening draft counter should advance without waiting");
game.player = { x: 100, y: 100, hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0, heal(n) { this.hp = Math.min(this.maxHp, this.hp + n); }, grantShield(n, dur) { this.shieldHp = n; this.shieldTimer = dur; }, addEnergy() {} };
game.endless = true; game.endlessLite = false; game._endlessDiffKey = "hell"; game._startingDrafts = 2; game._startingDraftsTotal = 3; game._inStartingDraft = true; game.state = "chipselect"; game._endlessT = 0; game._endlessStats = { picks: 0, drafts: 0 }; game._chipChoices = ["bonus:damage"]; game._chipRerolls = 0; game.floats = []; game.shockwaves = []; game.enemies = []; game.bonuses = {}; game.chips = {};
assert.strictEqual(game.chooseChip(0), true, "hell opening pick should be accepted");
assert.strictEqual(game.state, "chipselect", "hell opening pick should keep the draft panel open for the next pick");
assert.strictEqual(game._startingDrafts, 1, "hell opening pick should consume exactly one remaining draft");
assert(game._chipDraftReason.includes("第2/3件"), "hell opening pick should advance to the second immediate draft");
game.endless = false;
for (const [i, pool] of CONFIG.endless.pools.entries()) {
  assert(pool.enemies && pool.enemies.length, `endless pool ${i} is empty`);
  for (const type of pool.enemies) assert(enemyKeys.has(type), `pool ${i} references missing enemy ${type}`);
}

const eventKeys = CONFIG.endless.events.map(e => e.key);
unique(eventKeys, "endless events");
assert(eventKeys.includes("repairConvoy"), "endless events should include repair convoy pressure");
assert(eventKeys.includes("shieldWall"), "endless events should include shield carrier pressure");
assert(eventKeys.includes("phantomWing"), "endless events should include phantom pressure");
assert(eventKeys.includes("carrierRaid"), "endless events should include carrier split pressure");
assert(eventKeys.includes("annihilationOrder"), "endless events should include a kill-goal objective");
assert(eventKeys.includes("aceHunt"), "endless events should include an elite hunt objective");
assert(eventKeys.includes("noHitRun"), "endless events should include a no-hit objective");
assert(eventKeys.includes("crossfire"), "endless events should include a side bullet hazard");
assert(eventKeys.includes("shieldedAmbush"), "endless events should include shielded ambush pressure");
assert(eventKeys.includes("sniperCrossfire"), "endless events should include mixed sniper/crossfire pressure");
assert(eventKeys.includes("blackoutRaid"), "endless events should include jammer elite pressure");
assert(eventKeys.includes("rearAssault"), "endless events should include rear kamikaze pressure");
assert(eventKeys.includes("hornetPursuit"), "endless events should include homing missile pressure");
assert(eventKeys.includes("scorchedLane"), "endless events should include fire zone pressure");
assert(eventKeys.includes("frostNet"), "endless events should include ice slow pressure");
const routeNames = new Set(["主炮", "激光", "追踪", "导弹", "生存", "风险"]);
const drops = new Set(["power", "heal", "bomb", "wing", "chip"]);
for (const e of CONFIG.endless.events) {
  assert(e.name && e.sub, `event ${e.key} needs readable text`);
  if (e.routeBias) assert(routeNames.has(e.routeBias), `event ${e.key} has invalid routeBias ${e.routeBias}`);
  if (e.minTime != null) between(e.minTime, 0, 300, `event ${e.key} minTime`);
  if (e.enemyType) assert(enemyKeys.has(e.enemyType), `event ${e.key} references missing enemy ${e.enemyType}`);
  if (e.enemyChance != null) between(e.enemyChance, 0, 0.75, `event ${e.key} enemyChance`);
  if (e.eliteChance != null) between(e.eliteChance, 0, 0.9, `event ${e.key} eliteChance`);
  if (e.spawnBonus != null) between(e.spawnBonus, 0, 3, `event ${e.key} spawnBonus`);
  if (e.killGoal != null) between(e.killGoal, 6, 30, `event ${e.key} killGoal`);
  if (e.eliteGoal != null) between(e.eliteGoal, 2, 10, `event ${e.key} eliteGoal`);
  if (e.noHitGoal != null) assert.strictEqual(e.noHitGoal, true, `event ${e.key} noHitGoal should be true when present`);
  if (e.scoreBonus != null) between(e.scoreBonus, 0, 0.18, `event ${e.key} scoreBonus`);
  if (e.threatGainMult != null) between(e.threatGainMult, 1, 1.5, `event ${e.key} threatGainMult`);
  if (e.forceDrop) assert(drops.has(e.forceDrop), `event ${e.key} has invalid forceDrop ${e.forceDrop}`);
  if (e.powerupChanceAdd != null) between(CONFIG.endless.powerupChance + e.powerupChanceAdd, 0, 0.4, `event ${e.key} total powerup chance`);
  if (e.enemyHpMult != null) between(e.enemyHpMult, 0, 0.6, `event ${e.key} enemyHpMult`);
  if (e.laserEvery) {
    between(e.laserEvery, 3, 7, `event ${e.key} laserEvery`);
    between(e.warn || 0, 0.4, 1.2, `event ${e.key} laser warn`);
    between(e.width || 0, 20, 70, `event ${e.key} laser width`);
  }
  if (e.bulletEvery) {
    between(e.bulletEvery, 2.5, 6, `event ${e.key} bulletEvery`);
    between(e.bulletRows || 0, 3, 8, `event ${e.key} bulletRows`);
    between(e.bulletSpeed || 0, 160, 360, `event ${e.key} bulletSpeed`);
    between(e.bulletDamage || 0, 3, 12, `event ${e.key} bulletDamage`);
  }
}
const repairConvoy = CONFIG.endless.events.find(e => e.key === "repairConvoy");
assert.strictEqual(repairConvoy.enemyType, "support", "repair convoy should force support enemies");
assert(repairConvoy.minTime >= 90, "repair convoy should be a mid/late endless event");
const phantomWing = CONFIG.endless.events.find(e => e.key === "phantomWing");
assert.strictEqual(phantomWing.enemyType, "phantom", "phantom wing should force phantom enemies");
assert(phantomWing.minTime >= 120, "phantom wing should be a late endless event");
assert(phantomWing.routeBias, "phantom wing should bias draft choices");
const carrierRaid = CONFIG.endless.events.find(e => e.key === "carrierRaid");
assert.strictEqual(carrierRaid.enemyType, "carrier", "carrier raid should force carrier enemies");
assert(carrierRaid.minTime >= 150, "carrier raid should be a late endless event");
assert(CONFIG.enemy.carrier.spawns, "carrier raid should rely on carrier split adds");
const shieldWall = CONFIG.endless.events.find(e => e.key === "shieldWall");
assert.strictEqual(shieldWall.enemyType, "shieldCarrier", "shield wall should force shield carriers");
assert(shieldWall.minTime >= 120, "shield wall should be a mid/late endless event");
assert(CONFIG.endless.pools.slice(3).some(pool => pool.enemies.includes("shieldCarrier")), "late endless pools should include shield carriers");
const aceHunt = CONFIG.endless.events.find(e => e.key === "aceHunt");
assert.strictEqual(aceHunt.enemyType, "gunner", "ace hunt should force durable gunner elites");
assert(aceHunt.minTime >= 90, "ace hunt should be a mid endless event");
assert(aceHunt.eliteChance >= 0.6, "ace hunt should reliably spawn elites");
assert(aceHunt.eliteGoal >= 3, "ace hunt should require multiple elite kills");
const noHitRun = CONFIG.endless.events.find(e => e.key === "noHitRun");
assert(noHitRun.minTime >= 60, "no-hit run should not appear immediately");
assert.strictEqual(noHitRun.routeBias, "生存", "no-hit run should bias survival drafts");
assert.strictEqual(noHitRun.noHitGoal, true, "no-hit run should require no hits");
const crossfire = CONFIG.endless.events.find(e => e.key === "crossfire");
assert(crossfire.minTime >= 90, "crossfire should be a mid endless hazard");
assert.strictEqual(crossfire.routeBias, "生存", "crossfire should bias survival drafts");
const rearAssault = CONFIG.endless.events.find(e => e.key === "rearAssault");
assert.strictEqual(rearAssault.enemyType, "kamikaze", "rear assault should force kamikaze enemies");
assert(rearAssault.minTime >= 90, "rear assault should be a mid endless event");
assert.strictEqual(rearAssault.routeBias, "生存", "rear assault should bias survival drafts");
const hornetPursuit = CONFIG.endless.events.find(e => e.key === "hornetPursuit");
assert.strictEqual(hornetPursuit.enemyType, "beacon", "homing swarm should force beacon enemies");
assert(hornetPursuit.minTime >= beacon.homingMinTime, "homing swarm should start after homing is enabled");
const scorchedLane = CONFIG.endless.events.find(e => e.key === "scorchedLane");
assert.strictEqual(scorchedLane.enemyType, "mineLayer", "scorched lane should force mine layers");
assert(scorchedLane.minTime >= mineLayer.zoneMinTime, "scorched lane should start after fire zones are enabled");
const frostNet = CONFIG.endless.events.find(e => e.key === "frostNet");
assert.strictEqual(frostNet.enemyType, "tether", "frost net should force tether enemies");
assert(frostNet.minTime >= tether.zoneMinTime, "frost net should start after ice zones are enabled");
game.endless = true; game._endlessT = rearAssault.minTime; game.threat = 0; game.currentLevel = 0; game._rng = () => 0.999; game.player = { x: CONFIG.WIDTH / 2, y: CONFIG.HEIGHT - 100 };
const rearChaser = new Enemy("kamikaze", CONFIG.WIDTH / 2, 0);
assert.strictEqual(rearChaser.move, "rearChase", "kamikaze instances should default to rear chase");
assert(rearChaser.y > CONFIG.HEIGHT, "kamikaze should spawn below the playfield");
const rearStartY = rearChaser.y;
rearChaser.update(0.5);
assert(!rearChaser.dead, "kamikaze should not be culled before entering from behind");
assert(rearChaser.y < rearStartY, "kamikaze should move toward the player from behind");
const rearSpeedAt = mt => { rearChaser.x = CONFIG.WIDTH / 2; rearChaser.y = CONFIG.HEIGHT + rearChaser.radius; rearChaser.vx = 0; rearChaser.vy = 0; rearChaser._mt = mt; rearChaser.applyMove(0.1); return Math.hypot(rearChaser.vx, rearChaser.vy); };
const rearWarnSpeed = rearSpeedAt(1), rearBoostSpeed = rearSpeedAt(2.2), rearNormalSpeed = rearSpeedAt(4.8);
assert(rearBoostSpeed > rearWarnSpeed * 1.5, "kamikaze should accelerate after its 2 second warning");
assert(rearNormalSpeed < rearBoostSpeed, "kamikaze should return to normal speed after its boost");
game.player = { x: 220, y: 300, radius: 10, hp: 100, takeDamage(d) { this.hp -= d; }, applySlow(mult, dur) { this.slowMult = mult; this.slowTimer = dur; } };
const homingBullet = new EnemyBullet(120, 300, 0, 160, 5, { kind: "homing", radius: 7, speed: 160, turn: 4, life: 3 });
homingBullet.update(0.2);
assert(homingBullet.vx > 0, "enemy homing bullet should turn toward the player");
const fireZone = new EnemyBullet(game.player.x, game.player.y, 0, 0, 5, { kind: "fire", radius: 42, life: 2, tick: 0.6 });
fireZone.update(0.1);
assert.strictEqual(game.player.hp, 95, "fire zone should damage the player without disappearing immediately");
assert(!fireZone.dead, "fire zone should persist after a hit");
const iceZone = new EnemyBullet(game.player.x, game.player.y, 0, 0, 2, { kind: "ice", radius: 42, life: 2, slowMult: 0.55, slowDur: 1.2 });
iceZone.update(0.1);
assert(game.player.slowMult < 1 && game.player.slowTimer > 0, "ice zone should slow the player");
game.enemyBullets = []; game.endless = true; game._endlessT = beacon.homingMinTime; game.threat = 0; game._rng = () => 0.99;
const homingEnemy = new Enemy("beacon", 210, 0);
homingEnemy.y = 120; homingEnemy._homingSkillTimer = 0; homingEnemy.updateHomingSkill(0);
assert(game.enemyBullets.some(b => b.kind === "homing"), "beacon should spawn enemy homing bullets in endless");
game.enemyBullets = []; game._endlessT = mineLayer.zoneMinTime;
const fireEnemy = new Enemy("mineLayer", 210, 0);
fireEnemy.y = 140; fireEnemy._zoneTimer = 0; fireEnemy.updateZoneSkill(0);
assert(game.enemyBullets.some(b => b.kind === "fire"), "mineLayer should spawn fire zones in endless");
game.enemyBullets = []; game._endlessT = tether.zoneMinTime;
const iceEnemy = new Enemy("tether", 210, 0);
iceEnemy.y = 140; iceEnemy._zoneTimer = 0; iceEnemy.updateZoneSkill(0);
assert(game.enemyBullets.some(b => b.kind === "ice"), "tether should spawn ice zones in endless");
game.enemyBullets = []; game.floats = []; game.endless = true; game._endlessT = crossfire.minTime; game.threat = 0; game._endlessHazardT = 0; game._rng = () => 0.25;
assert.strictEqual(game.updateEndlessBulletEvent(0, crossfire), crossfire.bulletRows, "crossfire should spawn one side bullet row set");
assert.strictEqual(game.enemyBullets.length, crossfire.bulletRows, "crossfire should create enemy bullets");
assert(game.enemyBullets.every(b => b.vx > 0), "crossfire side bullets should move horizontally from the side");
assert(game.endlessEventHUDDetail(crossfire).includes("侧弹"), "crossfire HUD should show bullet cadence");
const recentEventKeys = CONFIG.endless.events.slice(0, 2).map(e => e.key);
game.endless = true; game._endlessT = 999; game._endlessEvent = null; game._endlessRecentEvents = recentEventKeys.slice(); game._endlessEventsSeen = []; game._endlessStats = { events: 0, hits: 0 }; game._rng = () => 0;
game.triggerEndlessEvent();
assert(!recentEventKeys.includes(game._endlessEvent.key), "endless event picker should avoid recent repeats when possible");
assert.strictEqual(game._endlessRecentEvents[0], game._endlessEvent.key, "endless event picker should remember the newest event");
assert(game._endlessRecentEvents.length <= 2, "endless event memory should stay short");
game.score = 0; game.threat = 0; game.bonuses = {}; game.chips = {}; game.floats = []; game._bonusRerolls = 0; game._endlessEventTimer = 0; game._endlessStats = { hits: 2 }; game._endlessEventStartHits = 1;
game.player = { x: 100, y: 100, shieldHp: 0, grantShield(n, dur) { this.shieldHp = n; this.shieldTimer = dur; } };
const eventHitGain = game.finishEndlessEvent(CONFIG.endless.events[0]);
assert.strictEqual(eventHitGain, CONFIG.endless.eventClearScore, "event clear should grant base score after hits");
assert.strictEqual(game.player.shieldHp, 0, "event clear should not grant clean shield after hits");
assert.strictEqual(game._bonusRerolls, 0, "hit event clear should not grant bonus rerolls");
assert.strictEqual(game._endlessStats.eventClears, 1, "event clear should be tracked");
assert.strictEqual(game._endlessStats.cleanEvents || 0, 0, "hit event clear should not count as clean");
assert.strictEqual(game._endlessStats.eventScore, eventHitGain, "event score should be tracked");
const killGoalEvent = CONFIG.endless.events.find(e => e.key === "annihilationOrder");
game.score = 0; game.floats = []; game._endlessStats = { hits: 0, kills: 3, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 0; game._endlessEventStartKills = 0;
assert.strictEqual(game.finishEndlessEvent(killGoalEvent), 0, "kill-goal event should fail without enough kills");
assert.strictEqual(game._endlessStats.eventClears, 0, "failed kill-goal event should not count as cleared");
assert.strictEqual(game._endlessStats.eventFails, 1, "failed kill-goal event should be tracked");
assert(game.floats.some(f => f.text.includes("目标未达成")), "failed kill-goal event should show feedback");
game._endlessStats.kills = 7; game._endlessEventStartKills = 3;
assert(game.endlessEventHUDDetail(killGoalEvent).includes("4/" + killGoalEvent.killGoal), "kill-goal event HUD should show live progress");
assert(game.endlessReviewTags({ telemetry: game._endlessStats, time: 60, bonuses: {} }).some(t => t.includes("目标失败")), "failed kill-goal events should appear in review tags");
game.score = 0; game.floats = []; game._endlessStats = { hits: 0, kills: killGoalEvent.killGoal, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 0; game._endlessEventStartKills = 0;
assert(game.finishEndlessEvent(killGoalEvent) > 0, "kill-goal event should clear after enough kills");
assert.strictEqual(game._endlessStats.eventClears, 1, "cleared kill-goal event should count as cleared");
assert(game.endlessEventHUDDetail(killGoalEvent).includes(killGoalEvent.killGoal + "/" + killGoalEvent.killGoal), "kill-goal event HUD should show objective");
game.score = 0; game.floats = []; game._endlessStats = { hits: 0, eliteKills: 1, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 0; game._endlessEventStartEliteKills = 0;
assert.strictEqual(game.finishEndlessEvent(aceHunt), 0, "elite-goal event should fail without enough elite kills");
assert.strictEqual(game._endlessStats.eventClears, 0, "failed elite-goal event should not count as cleared");
assert.strictEqual(game._endlessStats.eventFails, 1, "failed elite-goal event should be tracked");
assert(game.floats.some(f => f.text.includes("王牌未击破")), "failed elite-goal event should show feedback");
game._endlessStats.eliteKills = 3; game._endlessEventStartEliteKills = 1;
assert(game.endlessEventHUDDetail(aceHunt).includes("2/" + aceHunt.eliteGoal), "elite-goal event HUD should show live progress");
game.score = 0; game.floats = []; game._endlessStats = { hits: 0, eliteKills: aceHunt.eliteGoal, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 0; game._endlessEventStartEliteKills = 0;
assert(game.finishEndlessEvent(aceHunt) > 0, "elite-goal event should clear after enough elite kills");
assert.strictEqual(game._endlessStats.eventClears, 1, "cleared elite-goal event should count as cleared");
assert(game.endlessReviewTags({ telemetry: { eliteKills: 8 }, time: 90, bonuses: {} }).some(t => t.includes("精英猎手")), "elite kill review should tag elite hunters");
game.score = 0; game.floats = []; game._endlessStats = { hits: 2, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 1;
assert.strictEqual(game.finishEndlessEvent(noHitRun), 0, "no-hit event should fail after taking a hit");
assert.strictEqual(game._endlessStats.eventClears, 0, "failed no-hit event should not count as cleared");
assert.strictEqual(game._endlessStats.eventFails, 1, "failed no-hit event should be tracked");
assert(game.floats.some(f => f.text.includes("无伤失败")), "failed no-hit event should show feedback");
assert(game.endlessEventHUDDetail(noHitRun).includes("受击1/1"), "no-hit event HUD should show failed hit progress");
game.score = 0; game.floats = []; game._endlessStats = { hits: 1, eventClears: 0, eventScore: 0 }; game._endlessEventStartHits = 1;
assert(game.endlessEventHUDDetail(noHitRun).includes("受击0/1"), "no-hit event HUD should show clean progress");
assert(game.finishEndlessEvent(noHitRun) > 0, "no-hit event should clear without hits");
assert.strictEqual(game._endlessStats.eventClears, 1, "cleared no-hit event should count as cleared");
game.score = 0; game.floats = []; game._bonusRerolls = 0; game._endlessStats = { hits: 1 }; game._endlessEventStartHits = 1;
const eventCleanGain = game.finishEndlessEvent(CONFIG.endless.events[0]);
assert(eventCleanGain > eventHitGain, "clean event clear should grant bonus score");
assert(game.player.shieldHp >= CONFIG.endless.eventCleanShield, "clean event clear should grant shield");
assert.strictEqual(game._bonusRerolls, 1, "clean event clear should bank one bonus reroll");
assert.strictEqual(game._endlessStats.cleanEvents, 1, "clean event clear should be tracked");
game._endlessT = 60; game.beginChipDraft();
assert.strictEqual(game._chipRerolls, 2, "clean event reroll should apply to the next draft");
assert.strictEqual(game._bonusRerolls, 0, "bonus reroll bank should be consumed by the next draft");
assert(game.endlessReviewTags({ telemetry: game._endlessStats, time: 60, bonuses: {} }).some(t => t.includes("完美空域")), "clean event clears should appear in review tags");
assert(game.endlessReviewTags({ telemetry: { hits: 6, damageTaken: 120 }, time: 60, bonuses: {} }).some(t => t.includes("建议补生存")), "high damage review should suggest survival");
assert(game.endlessReviewTags({ telemetry: { bossKills: 0 }, time: 60, bonuses: {}, bossAffixes: ["蜂群·近卫舰"] }).some(t => t.includes("Boss输出")), "boss pressure review should suggest boss damage");
assert(game.endlessReviewTags({ telemetry: {}, time: 60, bonuses: { missileRack: 2 } }).some(t => t.includes("建议续构")), "near-ready route review should suggest route continuation");

const draftIds = CONFIG.chipOrder.map(k => "chip:" + k).concat(CONFIG.bonusOrder.map(k => "bonus:" + k));
const hasSurvivalDraft = () => game._chipChoices.some(id => id.startsWith("bonus:") && game.draftCardRoute(game.cardInfo(id)) === "生存");
const hasHpDraft = () => game._chipChoices.some(id => game.isHpDraftCard(id));
const hasMaxHpDraft = () => game._chipChoices.some(id => game.isMaxHpDraftCard(id));
const hasDraftRoute = route => game._chipChoices.some(id => game.draftCardRoute(game.cardInfo(id)) === route);
game.endless = true; game.player = { power: CONFIG.powerup.chipMinPower }; game._endlessEvent = null; game._endlessEventTimer = 0; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
assert.strictEqual(game.canDrop("chip"), false, "endless should use timed drafts instead of chip drops");
game.drawChipChoices();
assert(game._chipChoices.some(id => id.startsWith("bonus:")), "endless draft should include one permanent bonus option");
assert(hasSurvivalDraft(), "endless draft should include one survival/HP option");
assert(hasHpDraft(), "endless draft should include one HP/sustain option");
assert(hasMaxHpDraft(), "endless draft should include one max HP growth option");
assert(game.draftHpText(game.cardInfo("bonus:maxHp")).includes("血量"), "HP draft cards should show readable HP tag");
game.player = { power: CONFIG.powerup.chipMinPower, hp: 100, maxHp: 100 }; game._endlessT = 60; game._endlessStats = { hits: 0, damageTaken: 0 }; game.bonuses = {}; game.chips = {}; game._endlessEvent = null; game._endlessEventTimer = 0;
const armorPlatingBaseWeight = game.draftCardWeight("bonus:armorPlating");
game.player.hp = 35;
assert(game.hasSurvivalPressure(), "low HP should count as survival pressure");
assert(game.draftCardWeight("bonus:armorPlating") > armorPlatingBaseWeight, "survival pressure should weight survival cards higher");
assert(game.draftSurvivalText(game.cardInfo("bonus:armorPlating")).includes("生存"), "survival pressure cards should show reason text");
game.player.hp = 100; game._endlessStats = { hits: 5, damageTaken: 120 }; game._chipChoices = []; game._rng = () => 0.999;
assert(game.hasSurvivalPressure(), "high incoming damage should count as survival pressure");
game.drawChipChoices();
assert(game._chipChoices.some(id => game.draftSurvivalText(game.cardInfo(id)).includes("生存")), "survival pressure draft should include a survival recommendation");
game.bonuses = { missileRack: 1 }; game._chipChoices = []; game._rng = () => 0.999;
game.drawChipChoices();
assert(hasDraftRoute("导弹"), "draft should include an option for the current focused route");
assert(game.draftFocusText(game.cardInfo("bonus:explosivePayload")).includes("路线续构"), "focused route cards should show draft reason text");
game.boss = null;
const bossHunterBaseWeight = game.draftCardWeight("bonus:bossHunter");
game.boss = { dead: false };
assert(game.draftCardWeight("bonus:bossHunter") > bossHunterBaseWeight, "boss counter cards should be weighted higher during bosses");
assert(game.draftBossText(game.cardInfo("bonus:bossHunter")).includes("Boss"), "boss counter cards should show draft reason text");
game.boss = null;
game._endlessEvent = null; game._endlessEventTimer = 0; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
const shieldBreakerBaseWeight = game.draftCardWeight("bonus:shieldBreaker");
game._endlessEvent = shieldWall; game._endlessEventTimer = 10;
assert(game.hasShieldPressure(), "shield wall should count as shield pressure");
assert(game.draftCardWeight("bonus:shieldBreaker") > shieldBreakerBaseWeight, "shield pressure should weight shieldBreaker higher");
game.drawChipChoices();
assert(game._chipChoices.includes("bonus:shieldBreaker"), "shield pressure draft should include shieldBreaker");
assert(game.draftShieldText(game.cardInfo("bonus:shieldBreaker")).includes("破盾"), "shield pressure cards should show counter text");
game._endlessEvent = null; game._endlessEventTimer = 0; game.enemies = []; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
const eliteHunterBaseWeight = game.draftCardWeight("bonus:eliteHunter");
game._endlessEvent = aceHunt; game._endlessEventTimer = 10;
assert(game.hasElitePressure(), "ace hunt should count as elite pressure");
assert(game.draftCardWeight("bonus:eliteHunter") > eliteHunterBaseWeight, "elite pressure should weight eliteHunter higher");
game.drawChipChoices();
assert(game._chipChoices.includes("bonus:eliteHunter"), "elite pressure draft should include eliteHunter");
assert(game.draftEliteText(game.cardInfo("bonus:eliteHunter")).includes("精英"), "elite pressure cards should show counter text");
const realBurst = game.burst;
game.burst = () => {};
game.player = {
  x: 100, y: 100, hp: 50, maxHp: 100, energy: 0, shieldHp: 0,
  addEnergy(n) { this.energy += n; },
  heal(n) { this.hp = Math.min(this.maxHp, this.hp + n); },
  grantShield(n, dur) { this.shieldHp = n; this.shieldTimer = dur; },
};
game.floats = []; game.shockwaves = []; game.enemies = [];
game.enemyBullets = [{ x: 112, y: 100, dead: false }, { x: 310, y: 100, dead: false }];
assert.strictEqual(game.applyDraftPickBuff(game.cardInfo("bonus:missileInterceptor")), true, "missileInterceptor pick buff should apply");
assert(game.enemyBullets[0].dead && !game.enemyBullets[1].dead, "missileInterceptor pick buff should clear only nearby bullets");
game.applyDraftPickBuff(game.cardInfo("chip:chargeCore"));
assert.strictEqual(game.player.energy, CONFIG.chips.chargeCore.pickBuff.energy, "chargeCore pick buff should grant a small energy boost");
game.applyDraftPickBuff(game.cardInfo("chip:capacitor"));
assert(game.player.shieldHp > 0 && game.player.shieldTimer > 0, "capacitor pick buff should grant a small shield");
game.applyDraftPickBuff(game.cardInfo("bonus:repairLoop"));
assert(game.player.hp > 50, "repairLoop pick buff should immediately heal a little");
const energyBeforePickBuff = game.player.energy;
game.applyDraftPickBuff(game.cardInfo("bonus:painConverter"));
assert.strictEqual(game.player.energy, energyBeforePickBuff + CONFIG.bonuses.painConverter.pickBuff.energy, "painConverter pick buff should grant only a small energy boost");
game.enemyBullets = [{ x: 110, y: 100, dead: false }, { x: 260, y: 100, dead: false }];
game.applyDraftPickBuff(game.cardInfo("bonus:shieldBreaker"));
assert(game.enemyBullets[0].dead && !game.enemyBullets[1].dead, "shieldBreaker pick buff should add a small tactical clear");
assert(game.floats.some(f => f.text.includes("能量") || f.text.includes("护盾") || f.text.includes("修复") || f.text.includes("清弹")), "pick buffs should show float feedback");
game.burst = realBurst;
game.player = { power: CONFIG.powerup.chipMinPower, hp: 100, maxHp: 100 };
game.state = "playing"; game._endlessT = CONFIG.powerup.chipMinEndlessTime - 0.01; game._lastChipDraftAt = -Infinity; game._nextChipDraftAt = 0; game._endlessStats = { drafts: 0 };
assert.strictEqual(game.updateChipDraftTimer(), false, "draft timer should wait until the fixed delay");
game._endlessT = CONFIG.powerup.chipMinEndlessTime;
assert.strictEqual(game.updateChipDraftTimer(), true, "draft timer should start a draft at the fixed delay");
assert.strictEqual(game.state, "chipselect", "draft timer should open selection UI");
assert.strictEqual(game._endlessStats.drafts, 1, "timed draft should be counted once");
assert.strictEqual(game._nextChipDraftAt, CONFIG.powerup.chipMinEndlessTime + CONFIG.powerup.chipDraftInterval, "next draft should be one fixed interval later");
game.state = "playing"; game._endlessT = 90; game._lastChipDraftAt = 80; game._nextChipDraftAt = 120; game._pendingBossDraft = false; game._chipDraftReason = ""; game._endlessStats = { drafts: 0 };
assert.strictEqual(game.scheduleBossDraftReward({ x: 100, y: 100, radius: 40 }), true, "boss reward should pull the next draft earlier");
const bossRewardAt = 80 + CONFIG.powerup.chipMinDraftGap;
assert.strictEqual(game._nextChipDraftAt, bossRewardAt, "boss reward should respect the minimum draft gap");
assert.strictEqual(game._pendingBossDraft, true, "boss reward should mark the next draft reason");
game._endlessT = bossRewardAt - 0.01;
assert.strictEqual(game.updateChipDraftTimer(), false, "boss reward draft should still wait for its scheduled time");
game._endlessT = bossRewardAt;
assert.strictEqual(game.updateChipDraftTimer(), true, "boss reward draft should open at its scheduled time");
assert.strictEqual(game.state, "chipselect", "boss reward should open the selection UI");
assert(game._chipDraftReason.includes("Boss"), "boss reward draft should show a boss reward reason");
assert.strictEqual(game._pendingBossDraft, false, "boss reward marker should clear after opening");
assert.strictEqual(game._endlessStats.bossDrafts, 1, "boss reward should be tracked once");
game.state = "playing"; game._endlessT = 100; game._lastChipDraftAt = 96; game._nextChipDraftAt = 108; game._pendingBossDraft = false; game._endlessStats = {};
assert.strictEqual(game.scheduleBossDraftReward({ x: 100, y: 100, radius: 40 }), false, "boss reward should not make drafts too frequent");
assert.strictEqual(game._nextChipDraftAt, 108, "nearby scheduled draft should be kept");
game.state = "playing"; game._endlessT = 100; game._lastChipDraftAt = 96; game._nextChipDraftAt = 100; game._pendingBossDraft = false; game._endlessStats = { drafts: 0 };
assert.strictEqual(game.updateChipDraftTimer(), false, "draft timer should enforce the minimum draft gap");
game._endlessT = 96 + CONFIG.powerup.chipMinDraftGap;
assert.strictEqual(game.updateChipDraftTimer(), true, "draft timer should open after the minimum draft gap");
for (const e of CONFIG.endless.events.filter(e => e.routeBias)) {
  const matching = draftIds.filter(id => game.draftCardRoute(game.cardInfo(id)) === e.routeBias);
  assert(matching.length, `event ${e.key} routeBias ${e.routeBias} has no matching draft cards`);
  game.endless = true; game._endlessEvent = e; game._endlessEventTimer = 10; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
  game.drawChipChoices();
  assert(game._chipChoices.some(id => matching.includes(id)), `event ${e.key} draft should include one matching route card`);
  assert(game._chipChoices.some(id => id.startsWith("bonus:")), `event ${e.key} draft should include one permanent bonus option`);
  assert(hasSurvivalDraft(), `event ${e.key} draft should include one survival/HP option`);
  assert(hasHpDraft(), `event ${e.key} draft should include one HP/sustain option`);
  assert(hasMaxHpDraft(), `event ${e.key} draft should include one max HP growth option`);
}

const affixes = CONFIG.endless.boss.affixes;
unique(affixes.map(a => a.key), "boss affixes");
assert(affixes.some(a => a.key === "ewar"), "boss affixes should include electronic warfare pressure");
assert(affixes.some(a => a.key === "exposedCore"), "boss affixes should include weak point windows");
assert(affixes.some(a => a.key === "shieldEscort"), "boss affixes should include shield escort pressure");
assert(affixes.some(a => a.key === "phantomEscort"), "boss affixes should include phantom escort pressure");
assert(affixes.some(a => a.key === "swarmEscort"), "boss affixes should include swarm add pressure");
assert(affixes.some(a => a.key === "aceEscort"), "boss affixes should include elite ace pressure");
assert(affixes.some(a => a.key === "ironclad"), "boss affixes should include extra armor pressure");
assert(affixes.some(a => a.key === "sniperEscort"), "boss affixes should include sniper escort pressure");
assert(affixes.some(a => a.key === "prismArmor"), "boss affixes should include laser plus armor pressure");
assert(affixes.some(a => a.key === "crossBarrage"), "boss affixes should include dense barrage pressure");
assert(affixes.some(a => a.key === "rearGuard"), "boss affixes should include rear kamikaze pressure");
const shieldEscort = affixes.find(a => a.key === "shieldEscort");
game._endlessEvent = null; game._endlessEventTimer = 0; game.boss = { dead: false, affix: shieldEscort }; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
assert(game.hasShieldPressure(), "shield escort boss should count as shield pressure");
game.drawChipChoices();
assert(game._chipChoices.includes("bonus:shieldBreaker"), "shield escort boss draft should include shieldBreaker");
game.boss = null;
const aceEscort = affixes.find(a => a.key === "aceEscort");
assert.strictEqual(aceEscort.enemy, "gunner", "ace escort should spawn durable gunners");
assert(aceEscort.elite, "ace escort should spawn elite adds");
const rearGuard = affixes.find(a => a.key === "rearGuard");
assert.strictEqual(rearGuard.enemy, "kamikaze", "rear guard should spawn kamikaze adds");
game._endlessEvent = null; game._endlessEventTimer = 0; game.enemies = []; game.boss = { dead: false, affix: aceEscort }; game.bonuses = {}; game.chips = {}; game._chipChoices = []; game._rng = () => 0.999;
assert(game.hasElitePressure(), "ace escort boss should count as elite pressure");
game.drawChipChoices();
assert(game._chipChoices.includes("bonus:eliteHunter"), "ace escort boss draft should include eliteHunter");
const recentAffixKeys = affixes.slice(0, 2).map(a => a.key);
game._endlessT = 0; game._endlessRecentBossAffixes = recentAffixKeys.slice(); game._rng = () => 0;
const pickedAffix = game.pickEndlessBossAffix(affixes);
assert(!recentAffixKeys.includes(pickedAffix.key), "boss affix picker should avoid recent repeats when possible");
game.endless = true; game.endlessLite = false; game._endlessDiffKey = "hell"; game._endlessT = CONFIG.endless.dynamicHp.startTime;
const eliteCommand = game.pickEndlessBossAffix(affixes);
assert.strictEqual(eliteCommand.key, "eliteCommand", "dynamic hell bosses should force high-air elite command");
for (const a of affixes) {
  assert(a.name && a.desc, `boss affix ${a.key} needs readable text`);
  if (a.scoreMult) between(a.scoreMult, 1, 1.35, `boss affix ${a.key} scoreMult`);
  if (a.hpMult) between(a.hpMult, 0.05, 0.45, `boss affix ${a.key} hpMult`);
  if (a.fireMult) between(a.fireMult, 0.65, 1, `boss affix ${a.key} fireMult`);
  if (a.attack) {
    assert(["laser", "ring", "escort", "repair", "weak", "gravity", "prismBurst"].includes(a.attack), `boss affix ${a.key} has unknown attack ${a.attack}`);
    between(a.every || 0, 3, 12, `boss affix ${a.key} interval`);
  }
  if (a.count) between(a.count, 6, 24, `boss affix ${a.key} count`);
  if (a.speed) between(a.speed, 140, 360, `boss affix ${a.key} speed`);
  if (a.damageMult) between(a.damageMult, 0.5, 1.2, `boss affix ${a.key} damageMult`);
  if (a.maxAdds) between(a.maxAdds, 1, 6, `boss affix ${a.key} maxAdds`);
  if (a.adds) between(a.adds, 1, 4, `boss affix ${a.key} adds`);
  if (a.hpPct) between(a.hpPct, 0.05, 0.5, `boss affix ${a.key} hpPct`);
  if (a.enemy) assert(enemyKeys.has(a.enemy), `boss affix ${a.key} references missing enemy ${a.enemy}`);
  if (a.elite) assert(eliteTypes.includes(a.elite), `boss affix ${a.key} references missing elite ${a.elite}`);
  if (a.healPct) between(a.healPct, 0.01, 0.06, `boss affix ${a.key} healPct`);
  if (a.weakDamageMult) between(a.weakDamageMult, 0.15, 0.7, `boss affix ${a.key} weakDamageMult`);
}
const exposedCore = affixes.find(a => a.key === "exposedCore");
game.player = { hp: 100, maxHp: 100, shieldHp: 0 }; game.bonuses = {};
game.boss = { isBoss: true, hp: 100, maxHp: 100, affix: exposedCore, _weakTimer: exposedCore.dur };
assert(game.playerDamage(100, game.boss) > 100, "exposedCore should increase boss damage during weak window");
const weakDamage = game.playerDamage(100, game.boss);
game.bonuses = { weakScanner: 1 };
assert(game.playerDamage(100, game.boss) > weakDamage, "weakScanner should increase weak window damage");
game.floats = []; game.boss = { isBoss: true, x: 100, y: 100, radius: 40, hp: 100, maxHp: 100, affix: exposedCore, _weakTimer: 0 };
game.openBossWeakPoint(game.boss, exposedCore);
assert(game.boss._weakTimer > exposedCore.dur, "weakScanner should extend weak window duration");
game._rng = () => 0; game.endless = false; game.floats = []; game.shockwaves = []; game.enemies = [];
const drBoss = new Boss(0);
drBoss._invulnLeft = 0; drBoss._endlessDr = 0.5;
const drBossHp = drBoss.hp;
assert.strictEqual(drBoss.damage(100), false, "boss DR hit should not kill the boss");
assert.strictEqual(drBoss.hp, drBossHp - 50, "boss DR should reduce incoming damage");
const lockBoss = new Boss(0);
game.boss = lockBoss; game.enemies = [lockBoss];
assert.strictEqual(lockBoss._invulnTotal, CONFIG.bossInvuln.minCount, "boss lock count should start at configured minimum");
assert.strictEqual(lockBoss.damage(lockBoss.maxHp), false, "boss should lock HP instead of dying at the first lock threshold");
assert.strictEqual(lockBoss.hp, Math.round(lockBoss.maxHp * 2 / 3), "boss first lock should clamp HP to the first threshold");
between(lockBoss._invulnTimer, CONFIG.bossInvuln.minDuration, CONFIG.bossInvuln.maxDuration, "boss invuln timer");
assert(game.bossAffixHUDText(lockBoss).includes("无敌"), "boss HUD should show invulnerability timing");
const lockHp = lockBoss.hp;
lockBoss.damage(lockBoss.maxHp);
assert.strictEqual(lockBoss.hp, lockHp, "boss should ignore damage while invulnerable");
lockBoss._invulnTimer = 0;
assert.strictEqual(lockBoss.damage(lockBoss.maxHp), false, "boss should lock HP at the second threshold");
assert.strictEqual(lockBoss.hp, Math.round(lockBoss.maxHp / 3), "boss second lock should clamp HP to the second threshold");
lockBoss._invulnTimer = 0;
assert.strictEqual(lockBoss.damage(lockBoss.maxHp), true, "boss should die after all lock charges are spent");
game.endless = true; game.endlessLite = false; game._endlessDiffKey = "hell";
const hellLockBoss = new Boss(0);
assert.strictEqual(hellLockBoss.damage(hellLockBoss.maxHp), false, "hell endless boss should lock HP at the first threshold");
assert.strictEqual(hellLockBoss._invulnTimer, 5, "hell endless boss lock should last exactly 5s");
game._endlessT = CONFIG.endless.dynamicHp.startTime; game.boss = { dead: false };
const toughEnemy = new Enemy("medium", 120, 0, "straight", null);
toughEnemy.hp = toughEnemy.maxHp = 100; toughEnemy.eliteShield = toughEnemy.eliteShieldMax = 0;
assert.strictEqual(toughEnemy.damage(50), false, "dynamic hell enemy DR hit should not kill");
assert.strictEqual(toughEnemy.hp, 60, "dynamic hell enemy DR should reduce incoming damage by 20%");
const bossElite = new Enemy("gunner", 160, 0, "orbit", "berserker");
bossElite.hp = bossElite.maxHp = 100; bossElite._bossEliteDr = 0.5; bossElite._bossEliteMinLifeT = game._endlessT + 10;
assert.strictEqual(bossElite.damage(500), false, "boss elite should not die before its 10s minimum while boss lives");
assert.strictEqual(bossElite.hp, 1, "boss elite minimum life should clamp to 1 HP");
game.boss.dead = true;
assert.strictEqual(bossElite.damage(500), true, "boss elite should be killable after boss dies");
game.endless = false;
game.bonuses = {}; game.enemyBullets = [{ dead: false }]; game.lasers = [{ dead: false }]; game.powerups = []; game.floats = []; game.player = { power: CONFIG.powerup.chipMinPower };
const phaseBoss = { isBoss: true, x: 100, y: 120, radius: 40, hp: 100, maxHp: 100, _fireTimer: 0, def: { name: "PhaseTest", colors: ["#fff", "#ffd43b"], enterY: 120 } };
game.onBossPhaseChange(phaseBoss, 1);
assert(phaseBoss._weakTimer >= CONFIG.bossPhase.weakDuration, "boss phase change should open a weak window");
assert.strictEqual(phaseBoss._weakDamageMult, CONFIG.bossPhase.weakDamageMult, "boss phase weak window should use configured damage");
assert(game.playerDamage(100, phaseBoss) > 100, "boss phase weak window should increase damage");
assert(game.bossAffixHUDText(phaseBoss).includes("破甲"), "boss phase weak window should show HUD text without affix");
const phantomEscort = affixes.find(a => a.key === "phantomEscort");
game.enemies = []; game.floats = []; game.boss = { x: 220, y: 120, radius: 50 };
game.spawnBossEscort(game.boss, phantomEscort);
assert(game.enemies.some(e => e.type === "phantom"), "phantomEscort should spawn phantom adds");
const swarmEscort = affixes.find(a => a.key === "swarmEscort");
game.enemies = []; game.floats = []; game.boss = { x: 220, y: 120, radius: 50 };
assert.strictEqual(game.spawnBossEscort(game.boss, swarmEscort), swarmEscort.adds, "swarmEscort should spawn multiple adds");
assert.strictEqual(game.enemies.filter(e => e.type === "small").length, swarmEscort.adds, "swarmEscort should spawn small swarm adds");
game.enemies = []; game.floats = []; game.boss = { x: 220, y: 120, radius: 50 };
game.spawnBossEscort(game.boss, aceEscort);
assert(game.enemies.some(e => e.type === "gunner" && e.elite === aceEscort.elite), "aceEscort should spawn elite gunner adds");
game.endless = true; game.endlessLite = false; game._endlessDiffKey = "hell"; game._endlessT = CONFIG.endless.dynamicHp.startTime;
game.enemies = []; game.floats = []; game.boss = { x: 220, y: 120, radius: 50, maxHp: 10000 };
assert.strictEqual(game.spawnBossEscort(game.boss, eliteCommand), 1, "eliteCommand should spawn one high-air elite");
const commandAdd = game.enemies[0];
assert(commandAdd.elite && commandAdd.move === "orbit" && commandAdd.speed === 0 && commandAdd.y < 160, "eliteCommand add should hold in the upper screen");
assert.strictEqual(commandAdd.maxHp, 2000, "eliteCommand add HP should be 20% of boss HP");
assert.strictEqual(commandAdd._bossEliteDr, 0.5, "eliteCommand add should have 50% DR");
assert.strictEqual(commandAdd._bossEliteMinLifeT, CONFIG.endless.dynamicHp.startTime + 10, "eliteCommand add should have a 10s minimum life");
game.endless = true; game._rng = () => 0.999; game.player = { x: CONFIG.WIDTH / 2, y: CONFIG.HEIGHT - 100 };
game.enemies = []; game.floats = []; game.boss = { x: 220, y: 120, radius: 50 };
assert.strictEqual(game.spawnBossEscort(game.boss, rearGuard), rearGuard.adds, "rearGuard should spawn kamikaze adds");
assert(game.enemies.every(e => e.type === "kamikaze" && e.move === "rearChase"), "rearGuard adds should use rear chase movement");
assert(game.enemies.every(e => e.y > CONFIG.HEIGHT), "rearGuard adds should start behind the player");
game.floats = []; game._endlessBossAffixesSeen = []; game._endlessRecentBossAffixes = [];
game.applyEndlessBossAffix({ x: 100, radius: 40, hp: 100, maxHp: 100, score: 100, _fireScale: 1, def: { name: "Test", enterY: 120 } }, phantomEscort);
assert.strictEqual(game._endlessRecentBossAffixes[0], phantomEscort.key, "applied boss affix should be remembered");
const realSpawnEnemyBullet = game.spawnEnemyBullet;
let bossBulletCount = 0;
game.spawnEnemyBullet = function () { bossBulletCount++; };
game.endless = false; game.player = { x: 220, y: 700 };
runBossAttack({ x: 220, y: 120, radius: 50, bulletDamage: 1, _spiral: 0 }, { type: "ring", count: 8, speed: 200 });
const normalBossBullets = bossBulletCount;
game.endless = true; game.endlessLite = false; game._endlessDiffKey = "hell"; bossBulletCount = 0;
runBossAttack({ x: 220, y: 120, radius: 50, bulletDamage: 1, _spiral: 0 }, { type: "ring", count: 8, speed: 200 });
assert(bossBulletCount > normalBossBullets, "hell boss ring attacks should add more bullets");
game.spawnEnemyBullet = realSpawnEnemyBullet;

const bonusKeys = new Set(Object.keys(CONFIG.bonuses));
for (const key of CONFIG.bonusOrder) assert(bonusKeys.has(key), `bonusOrder references missing bonus ${key}`);
assert(!bonusKeys.has("pointDefense") && !CONFIG.bonusOrder.includes("pointDefense"), "pointDefense kill-clear bonus should stay removed");
for (const key of ["maxHp", "reinforcedHull", "armorPlating", "fieldRepair", "repairLoop", "repairPulse", "leech", "livingArmor", "medicalReservoir", "painConverter", "armorCaliber", "vitalReactor", "stableFire", "perfectLine", "shieldAmplifier", "shieldBreaker", "signalFilter"]) {
  assert(bonusKeys.has(key), `missing survival/build bonus ${key}`);
}
assert(bonusKeys.has("eliteHunter"), "missing elite counter build bonus");
assert(CONFIG.bonuses.armorCaliber.hpPerDamage > 0, "armorCaliber hpPerDamage must be positive");
between(CONFIG.bonuses.armorCaliber.maxDamage, 2, 8, "armorCaliber maxDamage");
assert(CONFIG.bonuses.vitalReactor.hpPerDamageMult > 0, "vitalReactor hpPerDamageMult must be positive");
between(CONFIG.bonuses.vitalReactor.damageMult, 0.02, 0.08, "vitalReactor damageMult");
between(CONFIG.bonuses.vitalReactor.maxDamageMult, 0.1, 0.4, "vitalReactor maxDamageMult");
between(CONFIG.bonuses.stableFire.hpThreshold, 0.55, 0.85, "stableFire hpThreshold");
between(CONFIG.bonuses.stableFire.damageMult, 0.08, 0.3, "stableFire damageMult");
between(CONFIG.bonuses.perfectLine.delay, 5, 12, "perfectLine delay");
between(CONFIG.bonuses.perfectLine.damageMult, 0.08, 0.25, "perfectLine damageMult");
between(CONFIG.bonuses.perfectLine.cooldownMult, 0.04, 0.16, "perfectLine cooldownMult");
between(CONFIG.bonuses.shieldAmplifier.damageMult, 0.08, 0.3, "shieldAmplifier damageMult");
between(CONFIG.bonuses.shieldBreaker.shieldDamageMult, 0.25, 1.0, "shieldBreaker shieldDamageMult");
between(CONFIG.bonuses.shieldBreaker.breakDamage, 3, 14, "shieldBreaker breakDamage");
between(CONFIG.bonuses.shieldBreaker.range, 100, 220, "shieldBreaker range");
between(CONFIG.bonuses.signalFilter.jamResist, 0.08, 0.3, "signalFilter jamResist");
between(CONFIG.bonuses.eliteHunter.eliteDamageMult, 0.15, 0.6, "eliteHunter eliteDamageMult");
between(CONFIG.bonuses.repairLoop.every, 8, 22, "repairLoop interval");
between(CONFIG.bonuses.repairLoop.healPct, 0.03, 0.12, "repairLoop healPct");
between(CONFIG.bonuses.repairLoop.shield, 4, 16, "repairLoop shield");
between(CONFIG.bonuses.repairPulse.damage, 4, 14, "repairPulse damage");
between(CONFIG.bonuses.repairPulse.range, 120, 220, "repairPulse range");
assert(bonusKeys.has("weakScanner"), "missing weak window build bonus");
between(CONFIG.bonuses.weakScanner.weakDamageMult, 0.1, 0.5, "weakScanner weakDamageMult");
between(CONFIG.bonuses.weakScanner.weakDuration, 0.2, 1.2, "weakScanner weakDuration");
between(CONFIG.bonuses.livingArmor.every, 8, 18, "livingArmor kill interval");
between(CONFIG.bonuses.livingArmor.hp, 1, 6, "livingArmor hp gain");
between(CONFIG.bonuses.livingArmor.maxHp, 18, 60, "livingArmor max HP per stack");
between(CONFIG.bonuses.medicalReservoir.hp, 1, 5, "medicalReservoir hp gain");
between(CONFIG.bonuses.medicalReservoir.maxHp, 12, 50, "medicalReservoir max HP per stack");
game.bonuses = {}; game._bonusStats = {}; game._bonusHpGain = {}; game.floats = []; game.player = { x: 100, y: 100, hp: 80, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
game.activateBonus("maxHp");
game.activateBonus("reinforcedHull");
assert(game._bonusHpGain.maxHp >= CONFIG.bonuses.maxHp.hp, "maxHp bonus should record HP gain");
assert(game._bonusHpGain.reinforcedHull > 0, "reinforcedHull should record HP gain");
assert(game.bonusHUDText("maxHp").includes("HP"), "HP bonus HUD should show gained HP");
assert(game.endlessReviewTags({ telemetry: {}, time: 60, bonuses: game.bonuses, bonusHpGain: game._bonusHpGain }).some(t => t.includes("HP")), "endless review should tag HP builds");
game.bonuses = { livingArmor: 1 }; game._bonusHpGain = {}; game.floats = []; game._bonusKillN = CONFIG.bonuses.livingArmor.every - 1; game.player = { x: 100, y: 100, hp: 80, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.triggerLivingArmorGrowth(), 0, "livingArmor should wait for its kill interval");
game._bonusKillN++;
assert.strictEqual(game.triggerLivingArmorGrowth(), CONFIG.bonuses.livingArmor.hp, "livingArmor should grow max HP on interval kills");
assert(game.player.maxHp > 100 && game._bonusHpGain.livingArmor > 0, "livingArmor should record gained max HP");
game._bonusHpGain.livingArmor = CONFIG.bonuses.livingArmor.maxHp;
game._bonusKillN += CONFIG.bonuses.livingArmor.every;
assert.strictEqual(game.triggerLivingArmorGrowth(), 0, "livingArmor should respect max HP cap");
game.score = 0; game.threat = 0; game._maxThreatLevel = 0; game.bonuses = { medicalReservoir: 1 }; game._bonusHpGain = {}; game.floats = []; game.enemies = []; game.chips = {};
game.player = { x: 100, y: 100, hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0, grantShield(n, dur) { this.shieldHp = n; this.shieldTimer = dur; } };
game.collectPowerup("heal");
assert.strictEqual(game.player.maxHp, 100 + CONFIG.bonuses.medicalReservoir.hp, "medicalReservoir should grow max HP from full HP heals");
assert.strictEqual(game._bonusHpGain.medicalReservoir, CONFIG.bonuses.medicalReservoir.hp, "medicalReservoir should record gained HP");
assert(game.player.shieldHp > 0, "medicalReservoir should keep the normal full HP shield reward");
assert(game.bonusHUDText("medicalReservoir").includes("HP"), "medicalReservoir HUD should show gained HP");
assert(game.draftStatPreviewText(game.cardInfo("bonus:medicalReservoir")).includes("HP"), "medicalReservoir draft preview should show HP cap");
game._bonusHpGain.medicalReservoir = CONFIG.bonuses.medicalReservoir.maxHp; const cappedHp = game.player.maxHp;
game.collectPowerup("heal");
assert.strictEqual(game.player.maxHp, cappedHp, "medicalReservoir should respect max HP cap");
game.endless = false; game.endlessLite = false; game._endlessDiffKey = "normal";
const repairLoop = CONFIG.bonuses.repairLoop;
game.bonuses = { repairLoop: 1 }; game.chips = {}; game.combo = 0; game.threat = 0; game._maxThreatLevel = 0; game._noHitT = 0; game._fieldRepairT = 0; game._repairLoopT = repairLoop.every - 0.01; game.floats = [];
game.player = { x: 100, y: 100, hp: 70, maxHp: 100, power: 1, overcharge: 0, shieldHp: 0, heal(n) { this.hp = Math.min(this.maxHp, this.hp + n); }, grantShield(n, dur) { this.shieldHp = n; this.shieldTimer = dur; } };
game.updateDepthSystems(0.02);
assert(game.player.hp > 70, "repairLoop should heal on interval");
game._repairLoopT = repairLoop.every; game.player.hp = game.player.maxHp; game.player.shieldHp = 0;
game.updateDepthSystems(0);
assert(game.player.shieldHp > 0, "repairLoop should grant shield at full HP");
assert(game.draftStatPreviewText(game.cardInfo("bonus:repairLoop")).includes("%"), "repairLoop draft preview should show healing");
game.bonuses = { repairPulse: 1 }; game.floats = []; game.shockwaves = []; game.enemies = [{ dead: false, x: 115, y: 100, radius: 10, hp: 20, maxHp: 20, damage(d) { this.hp -= d; if (this.hp <= 0) { this.dead = true; return true; } return false; } }];
game.player = { x: 100, y: 100, hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.triggerRepairPulse(game.player), 1, "repairPulse should hit nearby enemies");
assert(game.enemies[0].hp < 20 && game.shockwaves.length, "repairPulse should deal damage and show feedback");
assert(game.draftStatPreviewText(game.cardInfo("bonus:repairPulse")).includes("→"), "repairPulse draft preview should show damage gain");
game.endless = false; game.endlessLite = false; game._endlessDiffKey = "normal";
game.bonuses = { shieldAmplifier: 1 }; game.chips = {}; game.player = { hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.playerDamage(100), 100, "shieldAmplifier should not add damage without shield");
game.player.shieldHp = 10;
assert(game.playerDamage(100) > 100, "shieldAmplifier should add damage while shielded");
game.bonuses = { eliteHunter: 1 }; game.chips = {}; game.player = { hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.playerDamage(100, { hp: 100, maxHp: 100 }), 100, "eliteHunter should not add damage to normal enemies");
assert(game.playerDamage(100, { elite: "shield", hp: 100, maxHp: 100 }) > 100, "eliteHunter should add damage to elite enemies");
assert(game.draftStatPreviewText(game.cardInfo("bonus:eliteHunter")).includes("%"), "eliteHunter draft preview should show damage");
assert(game.bonusHUDText("eliteHunter").includes("%"), "eliteHunter HUD should show elite damage");
game.bonuses = { stableFire: 1 }; game.chips = {}; game.player = { hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert(game.playerDamage(100) > 100, "stableFire should add damage while HP is high");
assert(game.draftStatPreviewText(game.cardInfo("bonus:stableFire")).includes("%"), "stableFire draft preview should show damage");
assert(game.bonusHUDText("stableFire").includes("激活"), "stableFire HUD should show active state");
game.player.hp = 40;
assert.strictEqual(game.stableFireDamageMult(), 0, "stableFire should turn off at low HP");
assert(game.bonusHUDText("stableFire").includes("待机"), "stableFire HUD should show inactive state");
game.bonuses = { perfectLine: 1 }; game.chips = {}; game.enemies = []; game.boss = null; game._noHitT = CONFIG.bonuses.perfectLine.delay - 0.01; game.player = { x: 100, y: 100, hp: 100, maxHp: 100, baseMaxHp: 100, shieldHp: 0 };
assert.strictEqual(game.playerDamage(100), 100, "perfectLine should wait for no-hit delay");
assert.strictEqual(game.perfectLineValue("cooldownMult"), 0, "perfectLine cooldown should wait for no-hit delay");
assert(game.bonusHUDText("perfectLine").includes("s"), "perfectLine HUD should show pending timer");
game._noHitT = CONFIG.bonuses.perfectLine.delay;
assert(game.playerDamage(100) > 100, "perfectLine should add damage after no-hit delay");
assert(game.weaponCooldownMult() < 1, "perfectLine should speed weapons after no-hit delay");
assert(game.draftStatPreviewText(game.cardInfo("bonus:perfectLine")).includes("%"), "perfectLine draft preview should show gains");
assert(game.bonusHUDText("perfectLine").includes("%"), "perfectLine HUD should show active state");
game.endless = false; game.currentLevel = 1; game._rng = () => 0.999; game.bonuses = { shieldBreaker: 1 }; game.chips = {}; game.floats = []; game.shockwaves = [];
const shielded = new Enemy("shieldCarrier", 100, 0, "straight"); shielded.y = 100;
const splashTarget = { dead: false, x: 130, y: 100, radius: 12, hp: 30, maxHp: 30, damage(d) { this.hp -= d; if (this.hp <= 0) { this.dead = true; return true; } return false; } };
game.enemies = [shielded, splashTarget];
shielded.damage(CONFIG.enemy.shieldCarrier.shield / (1 + CONFIG.bonuses.shieldBreaker.shieldDamageMult));
assert(shielded.eliteShield <= 0, "shieldBreaker should break shields faster");
assert(game.shockwaves.length && game.floats.some(f => f.text.includes("破盾")), "shieldBreaker should show break feedback");
assert(splashTarget.hp < 30, "shieldBreaker should shock nearby enemies on break");
assert(game.draftStatPreviewText(game.cardInfo("bonus:shieldBreaker")).includes("%"), "shieldBreaker draft preview should show shield damage");
assert(game.bonusHUDText("shieldBreaker").includes("%"), "shieldBreaker HUD should show shield damage");
between(CONFIG.bonuses.painConverter.energyPerHp, 0.5, 2, "painConverter energyPerHp");
between(CONFIG.bonuses.painConverter.maxEnergy, 15, 60, "painConverter maxEnergy");
between(CONFIG.bonuses.comboBarrage.count, 1, 4, "comboBarrage count");
between(CONFIG.bonuses.comboBarrage.maxCount, 4, 12, "comboBarrage maxCount");
between(CONFIG.bonuses.sideCannons.maxPairs, 1, 4, "sideCannons maxPairs");
between(CONFIG.bonuses.laserSplitter.maxPairs, 1, 5, "laserSplitter maxPairs");
between(CONFIG.bonuses.clusterWarheads.maxCount, CONFIG.bonuses.clusterWarheads.count, 8, "clusterWarheads maxCount");
game.bonuses = { comboBarrage: 1 }; game.homingShots = []; game.floats = []; game.player = { x: 100, y: 100, radius: 15, overcharge: 0 };
game.comboMilestone(10);
assert.strictEqual(game.homingShots.length, CONFIG.bonuses.comboBarrage.count, "comboBarrage should fire homing shots on combo milestone");
assert(game.draftStatPreviewText(game.cardInfo("bonus:comboBarrage")).includes("2"), "comboBarrage draft preview should show shot count");
game.bonuses = {}; assert.strictEqual(game.missileVolleyBonus(), 0, "missile route should not add volley before ready");
game.bonuses = { missileRack: 3 }; assert.strictEqual(game.missileVolleyBonus(), 1, "missile route should add one missile when ready");
assert(game.routeEffectText().includes("导弹+1"), "missile route resonance text should show the extra missile");
game.bonuses = {}; const baseMissile = new Missile(100, 100, 0);
game.bonuses = { missileRack: 3 }; const routeMissile = new Missile(100, 100, 0);
assert(routeMissile.damage > baseMissile.damage && routeMissile.splash > baseMissile.splash, "missile route should increase missile damage and splash");
game.bonuses = {}; const baseLaser = new PlayerLaser(100, 100, 0);
game.bonuses = { laserLens: 3 }; const routeLaser = new PlayerLaser(100, 100, 0);
assert(routeLaser.damage > baseLaser.damage && routeLaser.life > baseLaser.life, "laser route should increase laser damage and duration");
game.endless = false; game.endlessLite = false; game.state = "playing"; game.ship = CONFIG.ships.balanced; game.diff = CONFIG.difficulties.normal;
game.chips = {}; game.bonuses = {}; game.floats = []; game.player = new Player();
game.player.power = CONFIG.player.maxPower; game.player.overcharge = CONFIG.player.maxOvercharge;
const mainDamageBeforePower = game.mainBulletDamage(null, "main");
const wingDamageBeforePower = game.mainBulletDamage(null, "wing");
const laserDamageBeforePower = new PlayerLaser(100, 100, 0).damage;
game.collectPowerup("power");
assert.strictEqual(game.player.powerDamage, 1, "overflow power should permanently add power damage");
assert.strictEqual(game.mainBulletDamage(null, "main"), mainDamageBeforePower + 1, "overflow power should increase main gun damage");
assert.strictEqual(game.mainBulletDamage(null, "wing"), wingDamageBeforePower, "overflow power should not increase wingman bullets");
assert.strictEqual(new PlayerLaser(100, 100, 0).damage, laserDamageBeforePower + 1, "overflow power should increase laser damage");
game.player.wings = CONFIG.wingMax;
const mainDamageBeforeWing = game.mainBulletDamage(null, "main");
const wingDamageBeforeWing = game.mainBulletDamage(null, "wing");
game.collectPowerup("wing");
assert.strictEqual(game.player.wingDamage, 1, "overflow wing should permanently add wingman damage");
assert.strictEqual(game.mainBulletDamage(null, "main"), mainDamageBeforeWing, "overflow wing should not increase main gun damage");
assert.strictEqual(game.mainBulletDamage(null, "wing"), wingDamageBeforeWing + 1, "overflow wing should increase wingman bullets");
const realSpawnPlayerLaser = game.spawnPlayerLaser, realSpawnShockwave = game.spawnShockwave;
game.endless = false; game.endlessLite = false; game.state = "playing"; game.ship = CONFIG.ships.balanced; game.diff = CONFIG.difficulties.normal;
game.chips = {}; game.bonuses = {}; game.playerLasers = []; game.shockwaves = []; game.floats = [];
game.player = new Player(); game.player.power = CONFIG.charge.minPower; game.player._fireTimer = 999; game.player._flameTimer = 999;
sandbox.input.targetX = game.player.x; sandbox.input.targetY = game.player.y;
game.spawnPlayerLaser = function(x, y, overcharge) { this.playerLasers.push({ x, y, overcharge }); };
game.spawnShockwave = function(x, y, maxR, color) { this.shockwaves.push({ x, y, maxR, color }); };
game.player.update(0.01);
assert(game.player.charging, "charge weapon should start charging automatically when ready");
game.player.charge = CONFIG.charge.max - 0.01;
game.player.update(0.02);
assert.strictEqual(game.player.charging, false, "charge weapon should auto release at full charge");
assert.strictEqual(game.player.charge, 0, "auto released charge should reset charge meter");
assert.strictEqual(game.playerLasers.length, 1, "auto released charge should fire one laser");
assert(game.player.chargeCooldown > 0, "auto released charge should enter cooldown");
game.spawnPlayerLaser = realSpawnPlayerLaser; game.spawnShockwave = realSpawnShockwave;
game.bonuses = {}; assert.strictEqual(game.homingVolleyBonus(), 0, "homing route should not add shots before ready");
game.bonuses = { swarmCore: 3 }; assert.strictEqual(game.homingVolleyBonus(), 1, "homing route should add one homing shot when ready");
assert(game.homingCooldownMult() < 1 && game.routeEffectText().includes("追踪+1"), "homing route should speed up and show resonance text");
game.bonuses = { missileRack: 2 };
assert(game.routeProgressText().includes("/7"), "route progress should show resonance threshold");
assert(game.routePreviewText(game.cardInfo("bonus:missileRack")).includes("解锁共鸣"), "draft route preview should show resonance unlock");

console.log(`balance check passed: ${CONFIG.endless.events.length} events, ${affixes.length} boss affixes, ${CONFIG.bonusOrder.length} bonuses`);
